"""IU X-Ray finding representation: MeSH/Problems terms -> the frozen 14-class classifier vocabulary.

Mapping rules live in iu_finding_mapping.json (generated by scripts/r1_01_dataset_split_corpus.py from
configs/iu_concept_lexicon.yaml plus explicit conditional / ambiguous decisions). Terms that are genuinely
ambiguous or outside the vocabulary are never mapped; they are stored separately.

Evaluation set of a study (used by Jaccard / nDCG):
    abnormal mapped findings (subset of the 13 non-No-Finding classes), or {No Finding} when the study is indexed
    'normal' and has no mapped abnormal finding; otherwise the study has NO usable representation (None).
"""

from __future__ import annotations

from src.classification.labels import LABELS, NO_FINDING

ABNORMAL = [l for l in LABELS if l != NO_FINDING]


def parse_mesh(value: object) -> list[tuple[str, list[str]]]:
    """'Opacity/lung/base;Cardiomegaly/mild' -> [('Opacity', ['lung','base']), ('Cardiomegaly', ['mild'])]."""
    if value is None or (isinstance(value, float) and value != value):
        return []
    out = []
    for part in str(value).split(";"):
        bits = [b.strip() for b in part.split("/")]
        if bits and bits[0]:
            out.append((bits[0], [b.lower() for b in bits[1:] if b]))
    return out


def map_study(mesh_value: object, mapping: dict) -> dict:
    """Mapped findings of one study (never guesses: ambiguous / unknown terms are returned separately)."""
    found, uncertain, unmapped, normal, no_index = set(), [], [], False, False
    for term, quals in parse_mesh(mesh_value):
        if term.lower() == "normal":
            normal = True
        elif term.lower() == "no indexing":
            no_index = True
        elif term in mapping["direct"]:
            found.add(mapping["direct"][term])
        else:
            hit = None
            for rule in mapping["conditional"]:
                if rule["term"] == term and any(q in rule["any_qualifier"] for q in quals):
                    hit = rule["class"]
            if hit:
                found.add(hit)
            elif term in mapping["uncertain"]:
                uncertain.append(term)
            else:
                unmapped.append(term)
    ordered = [l for l in ABNORMAL if l in found]
    return {"findings": ordered, "normal": normal, "no_indexing": no_index, "uncertain_terms": sorted(set(uncertain)),
            "unmapped_terms": sorted(set(unmapped))}


def eval_set(findings: list[str], normal: bool) -> frozenset | None:
    """Evaluation finding set; None when the study has no usable representation."""
    if findings:
        return frozenset(findings)
    return frozenset({NO_FINDING}) if normal else None
