"""Write THRESHOLD_OPTIMIZATION.md from the stored C3 artifacts (numbers are read, not typed).

    .venv\\Scripts\\python.exe -m scripts.c3_write_report
"""

from __future__ import annotations

import json

import numpy as np
import pandas as pd

from scripts.c3_threshold_optimization import COMMON, EXPECTED_C2B, N_BOOT, BOOT_SEED, RARE, SANITY, UNSTABLE
from src.classification.labels import LABELS, NO_FINDING, PATHOLOGY_LABELS
from src.classification.operating_points import apply_thresholds, load_threshold_file
from src.classification.serialization import load_predictions_npz
from src.utils.config import PROJECT_ROOT

E = PROJECT_ROOT / "results/classification/experiments"
O = E / "c3_threshold_optimization"
f3 = lambda v: "n/a" if v is None or not np.isfinite(v) else f"{v:.3f}"  # noqa: E731
f4 = lambda v: "n/a" if v is None or not np.isfinite(v) else f"{v:.4f}"  # noqa: E731
sg = lambda v: "n/a" if v is None or not np.isfinite(v) else f"{v:+.3f}"  # noqa: E731
pct = lambda v: f"{v:.1f}%"  # noqa: E731


def main() -> int:
    rd = lambda n: pd.read_csv(O / n, float_precision="round_trip")  # noqa: E731
    info = json.loads((O / "input_verification.json").read_text(encoding="utf-8"))
    rep = json.loads((O / "reproduced_c2b_metrics.json").read_text(encoding="utf-8"))
    res = json.loads((O / "c3_results.json").read_text(encoding="utf-8"))
    wide, san, boot, macro = rd("threshold_comparison.csv"), rd("threshold_sanity.csv"), rd("threshold_bootstrap.csv"), rd("macro_operating_summary.csv")
    yt, f1t, bt = rd("youden_table.csv"), rd("f1_optimal_table.csv"), rd("baseline_050_table.csv")
    nf = json.loads((O / "no_finding_consistency.json").read_text(encoding="utf-8"))
    pred = load_predictions_npz(E / "c2b_sqrt_weighted_bce/evaluation/fp32_strict/validation_predictions.npz")
    p, raw, v = pred["probs"], pred["raw_labels"], pred["valid"]
    ck = info["checkpoint"]
    thr_y = load_threshold_file(O / "thresholds_youden.json")
    thr_f = load_threshold_file(O / "thresholds_f1.json")
    pols = {"0.50": np.full(14, 0.5), "Youden J": thr_y, "F1-optimal": thr_f}
    perimg = {k: apply_thresholds(p, t) for k, t in pols.items()}
    actual_pos = (raw == 1)
    m = macro.set_index("policy")
    W = wide.set_index("observation")
    L = []
    A = L.append

    A("# C3: per-class threshold optimisation and operating-point evaluation")
    A("")
    A("_Generated by `scripts/c3_write_report.py` from the stored artifacts. No model was trained or re-run: the canonical C2-B validation scores were verified and reused. The locked test split was not opened._")
    A("")
    A("## 1. Objective")
    A("")
    A("C2 asked which loss **ranks** positives above negatives better. C3 asks a different question: **at what score should each of the 14 findings be called positive?**")
    A("")
    A("A single 0.50 cut-off is not automatically appropriate here, for three reasons:")
    A("- The 14 outputs are independent sigmoid scores of a multi-label model. Nothing ties them to a common scale.")
    A("- Prevalence ranges from 1.3% to 56%, so an equally calibrated score would sit far below 0.50 for rare findings.")
    A("- Loss weighting (here √-weighted BCE) changes the score scale in a class-dependent way.")
    A("")
    A("The task therefore replaces the universal 0.50 with class-specific thresholds learned on the validation split. **AUROC and AUPRC are threshold-independent and therefore remain unchanged by threshold selection.** The C2-B values are reproduced below only as a check.")
    A("")
    A("## 2. Inputs and provenance")
    A("")
    A("| Item | Value |")
    A("|---|---|")
    A(f"| Model | C2-B: DenseNet121 (14 logits), loss = `{ck['training_loss']['type']}` with `{ck['training_loss']['pos_weight_tempering']}` tempering (training-split weights) |")
    A(f"| Checkpoint | `{ck['path']}` ({ck['size_bytes']:,} bytes) |")
    A(f"| Checkpoint SHA-256 | `{ck['sha256_recomputed']}` (recomputed; matches the recorded hash: {ck['sha256_match']}) |")
    A(f"| Code commit stored in checkpoint | `{ck['git_commit_in_checkpoint']}` |")
    A(f"| Selected training epoch | {ck['selected_epoch']} (by `{ck['selection_metric']}` = {ck['selection_metric_value']:.4f}) |")
    A(f"| Validation set | {info['validation']['n_images']:,} frontal images from {info['validation']['n_patients']:,} patients |")
    A(f"| Evaluation precision | `{info['evaluation_precision_policy']}` (fp32, TF32 off); stored predictions are bit-identical across two runs: {info['evaluation_determinism_bit_identical']} |")
    A(f"| Label policy | uncertain → excluded from all metrics ({info['validation']['n_uncertain_excluded_entries']:,} entries); blank → negative |")
    A(f"| Same rows and masks as the other C2 arms | {info['validation']['rows_and_masks_identical_to_c2a']} |")
    A(f"| Train ∩ validation patients | {info['validation']['train_val_patient_overlap']} |")
    A(f"| Test patients present in validation scores | {info['validation']['test_patients_in_validation']} |")
    A(f"| Labels re-read from the source CSV equal the stored labels | {info['validation']['labels_reread_from_source_csv_identical']} |")
    A(f"| Config equals the C2-B base config | {info['config_matches_c2_base_config']} |")
    A("")
    A("**Class order (fixed, used for every vector, table and file):** " + ", ".join(f"{i + 1}. {l}" for i, l in enumerate(LABELS)) + ".")
    A("")
    A("**Metric reproduction (precondition).** Recomputed from the stored scores with sklearn:")
    A("")
    A("| Metric | Recomputed | Saved C2-B value | Abs. diff | Task's approximate value |")
    A("|---|---:|---:|---:|---:|")
    for k in ("macro_auroc", "micro_auroc", "macro_auprc", "micro_auprc"):
        A(f"| {k.replace('_', ' ').title().replace('Auroc', 'AUROC').replace('Auprc', 'AUPRC')} | {rep['recomputed'][k]:.6f} | {rep['saved'][k]:.6f} | {rep['abs_diff'][k]:.1e} | ≈ {EXPECTED_C2B[k]} |")
    A("")
    A(f"All 14 per-class AUROC/AUPRC values also match (max abs. difference {rep['max_per_class_abs_diff']:.1e}). The earlier C1-era Youden implementation (`src/classification/thresholds.py`) selects identical thresholds on these scores (max abs. difference {res['cross_check_vs_earlier_youden_impl']['max_abs_diff_vs_src.classification.thresholds']:.1e}), so the new tie rule changed nothing here.")
    A("")
    A("## 3. Method")
    A("")
    A("Decision rule: a finding is positive when `score >= threshold`. Candidate thresholds are the distinct validation scores of that class, evaluated on valid (non-uncertain) entries only. Counts are integers, so ties are decided exactly.")
    A("")
    A("- **Default 0.50.** Applied to every class as the baseline.")
    A("- **Youden J (primary).** `J = Sensitivity + Specificity − 1 = TPR − FPR`; threshold = argmax J per class. Tie rule: higher sensitivity, then higher threshold. If J ≤ 0 everywhere, or a class has no positives or no negatives, the threshold is reported as undefined instead of being invented.")
    A("- **F1-optimal (secondary).** `F1 = 2TP / (2TP + FP + FN)`; threshold = argmax F1. Tie rule: higher recall, then higher threshold. It is a sensitivity analysis only.")
    A(f"- **Patient bootstrap.** {N_BOOT:,} resamples of the {info['validation']['n_patients']:,} validation patients with replacement (all of a patient's images move together; the same resample is used for all 14 classes; seed {BOOT_SEED}). The Youden threshold is recomputed in each resample.")
    A(f"- **Pre-declared rules (written into the code before any C3 number was seen).** Threshold flagged low if < {SANITY['low']}, high if > {SANITY['high']}, near 0 if < {SANITY['near_zero']}, near 1 if > {SANITY['near_one']}. Bootstrap interval flagged unstable if its 95% width > {UNSTABLE['max_interval_width']} or > {UNSTABLE['max_width_over_median']}× the bootstrap median. Rare/common groups are the ones used in C2.")
    A("")
    A("## 4. Final 14 Youden J thresholds (validation)")
    A("")
    A("| Observation | Prevalence | **Threshold** | J | Sensitivity | Specificity | Precision | F1 | Balanced acc. | TP | FP | TN | FN |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for r in yt.itertuples():
        A(f"| {r.observation} | {f3(r.prevalence)} | **{f4(r.threshold)}** | {f3(r.youden_j)} | {f3(r.sensitivity)} | {f3(r.specificity)} | {f3(r.precision)} | {f3(r.f1)} | {f3(r.balanced_accuracy)} | {int(r.tp):,} | {int(r.fp):,} | {int(r.tn):,} | {int(r.fn):,} |")
    A("")
    A("Full-precision values: `thresholds_youden.json`. Figure: `figures/fig1_youden_thresholds.png`.")
    A("")
    A("## 5. Default 0.50 vs Youden")
    A("")
    A("### Baseline at 0.50")
    A("")
    A("| Class | Prevalence | Thr | TP | FP | TN | FN | Precision | Recall | Specificity | F1 | Balanced acc. |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for r in bt.itertuples():
        A(f"| {r.observation} | {f3(r.prevalence)} | 0.50 | {int(r.tp):,} | {int(r.fp):,} | {int(r.tn):,} | {int(r.fn):,} | {f3(r.precision)} | {f3(r.recall)} | {f3(r.specificity)} | {f3(r.f1)} | {f3(r.balanced_accuracy)} |")
    A("")
    A("### Three-way comparison and change from 0.50 to Youden")
    A("")
    A("| Class | Thr 0.50 | Thr Youden | Thr F1 | Recall@0.50 | Recall@J | Precision@0.50 | Precision@J | Spec@0.50 | Spec@J | F1@0.50 | F1@J | ΔPrec | ΔRecall | ΔSpec | ΔF1 | ΔBalAcc |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for lab in LABELS:
        r = W.loc[lab]
        dspec = r["specificity_youden"] - r["specificity_050"]
        A(f"| {lab} | 0.50 | {f3(r.thr_youden)} | {f3(r.thr_f1)} | {f3(r.recall_050)} | {f3(r.recall_youden)} | {f3(r.precision_050)} | {f3(r.precision_youden)} | {f3(r.specificity_050)} | {f3(r.specificity_youden)} | {f3(r.f1_050)} | {f3(r.f1_youden)} | {sg(r.delta_precision_050_to_youden)} | {sg(r.delta_recall_050_to_youden)} | {sg(dspec)} | {sg(r.delta_f1_050_to_youden)} | {sg(r.delta_balanced_accuracy_050_to_youden)} |")
    A("")
    A("### Macro operating-point summary (14 classes, unweighted mean)")
    A("")
    A("| Policy | Macro precision | Macro recall | Macro specificity | Macro F1 | Macro balanced acc. |")
    A("|---|---:|---:|---:|---:|---:|")
    for pol, name in (("baseline_050", "0.50"), ("youden", "Youden J"), ("f1_optimal", "F1-optimal")):
        r = m.loc[pol]
        A(f"| {name} | {f3(r.macro_precision)} | {f3(r.macro_recall)} | {f3(r.macro_specificity)} | {f3(r.macro_f1)} | {f3(r.macro_balanced_accuracy)} |")
    A("")
    A("All 14 classes are defined for every metric under every policy. **AUROC and AUPRC are not recalculated here:** they are threshold-independent and remain exactly as in §2.")
    A("")
    a, b_ = m.loc["baseline_050"], m.loc["youden"]
    A("What Youden does, and what it costs:")
    A(f"- **Recall:** macro recall {f3(a.macro_recall)} → {f3(b_.macro_recall)}; balanced accuracy {f3(a.macro_balanced_accuracy)} → {f3(b_.macro_balanced_accuracy)}.")
    A(f"- **Costs:** macro precision {f3(a.macro_precision)} → {f3(b_.macro_precision)}, macro specificity {f3(a.macro_specificity)} → {f3(b_.macro_specificity)}, and macro F1 {f3(a.macro_f1)} → {f3(b_.macro_f1)}.")
    dba = W["delta_balanced_accuracy_050_to_youden"]
    A(f"- **So Youden is not an F1 improvement.** It buys sensitivity with false positives. Balanced accuracy rises in {int((dba > 0).sum())} of 14 classes (by {dba.min():+.3f} to {dba.max():+.3f}); the gain is negligible (≤ +0.004) for " + ", ".join(l for l in LABELS if 0 < dba[l] <= 0.004) + f". F1 falls in {int((W['delta_f1_050_to_youden'] < 0).sum())} of 14 classes.")
    A("")
    A("## 6. F1-optimal thresholds (sensitivity analysis)")
    A("")
    A("| Class | Thr 0.50 | Thr Youden | **Thr F1** | Recall@F1 | Precision@F1 | Spec@F1 | F1@F1 | BalAcc@F1 |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|---:|")
    for r in f1t.itertuples():
        A(f"| {r.observation} | 0.50 | {f3(W.loc[r.observation, 'thr_youden'])} | **{f3(r.threshold)}** | {f3(r.recall)} | {f3(r.precision)} | {f3(r.specificity)} | {f3(r.f1)} | {f3(r.balanced_accuracy)} |")
    A("")
    c = m.loc["f1_optimal"]
    n_hi = int((W["thr_f1"] > W["thr_youden"]).sum())
    A(f"F1-optimal thresholds are higher than the Youden thresholds in {n_hi} of 14 classes (macro F1 {f3(c.macro_f1)}, recall {f3(c.macro_recall)}, precision {f3(c.macro_precision)}, specificity {f3(c.macro_specificity)}). F1 penalises false positives through precision, whereas Youden normalises them by the (large) negative count, so the two criteria disagree most where negatives vastly outnumber positives. **The operating point is therefore sensitive to the selection criterion, not just to the data.** This analysis is not used to replace Youden: the task fixes Youden as the primary rule, and F1 favours whichever trade-off the metric happens to reward.")
    A("")
    A("## 7. Rare vs common classes")
    A("")
    A("Groups are the C2 groups, not redefined after seeing these results: rare = " + ", ".join(RARE) + "; common = " + ", ".join(COMMON) + ".")
    A("")
    A("| Rare class | Prevalence | Recall@0.50 | Recall@J | Precision@0.50 | Precision@J | Spec@J | Youden thr |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|")
    for lab in RARE:
        r = W.loc[lab]
        A(f"| {lab} | {f3(r.prevalence)} | {f3(r.recall_050)} | {f3(r.recall_youden)} | {f3(r.precision_050)} | {f3(r.precision_youden)} | {f3(r.specificity_youden)} | {f3(r.thr_youden)} |")
    A("")
    A("| Common class | Prevalence | Recall@0.50 | Recall@J | Precision@0.50 | Precision@J | Spec@J | Youden thr |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|")
    for lab in COMMON:
        r = W.loc[lab]
        A(f"| {lab} | {f3(r.prevalence)} | {f3(r.recall_050)} | {f3(r.recall_youden)} | {f3(r.precision_050)} | {f3(r.precision_youden)} | {f3(r.specificity_youden)} | {f3(r.thr_youden)} |")
    A("")
    mr = {k: float(np.mean([W.loc[l, k] for l in RARE])) for k in ("recall_050", "recall_youden", "precision_050", "precision_youden", "specificity_youden")}
    mc = {k: float(np.mean([W.loc[l, k] for l in COMMON])) for k in ("recall_050", "recall_youden", "precision_050", "precision_youden", "specificity_youden")}
    A(f"- **Rare classes (mean of 6):** recall {f3(mr['recall_050'])} → {f3(mr['recall_youden'])}; precision {f3(mr['precision_050'])} → {f3(mr['precision_youden'])}; specificity at the Youden point {f3(mr['specificity_youden'])}.")
    A(f"- **Common classes (mean of 5):** recall {f3(mc['recall_050'])} → {f3(mc['recall_youden'])}; precision {f3(mc['precision_050'])} → {f3(mc['precision_youden'])}; specificity {f3(mc['specificity_youden'])}.")
    A("")
    A(f"**The trade-off, both sides.** At 0.50 the rare classes are almost never called (recall {min(W.loc[l, 'recall_050'] for l in RARE):.2f}–{max(W.loc[l, 'recall_050'] for l in RARE):.2f}), so most true cases are missed. Youden recovers {min(W.loc[l, 'recall_youden'] for l in RARE):.0%}–{max(W.loc[l, 'recall_youden'] for l in RARE):.0%} of them. The price is false alarms on a far larger negative pool:")
    for lab in ("Pleural Other", "Pneumonia", "Fracture", "Lung Lesion"):
        r = yt.set_index("observation").loc[lab]
        A(f"  - {lab}: {int(r.tp):,} true positives against {int(r.fp):,} false positives (about {r.fp / r.tp:.0f} false alarms per correct call; precision {f3(r.precision)}).")
    A("")
    A("Whether that is \"better\" depends on the downstream cost of a missed finding versus a spurious one, which C3 does not decide.")
    A("")
    A("For the common classes the effect varies with how far the threshold moves: " + "; ".join(f"{l} (thr {W.loc[l, 'thr_youden']:.3f}) recall {W.loc[l, 'recall_050']:.2f} → {W.loc[l, 'recall_youden']:.2f}, precision {W.loc[l, 'precision_050']:.2f} → {W.loc[l, 'precision_youden']:.2f}" for l in COMMON) + ". Classes whose threshold stays near 0.50 (Lung Opacity, Support Devices, Pleural Effusion) change little; Atelectasis and Edema, whose thresholds drop to about 0.30, change a lot.")
    A("")
    A("## 8. Threshold sanity check")
    A("")
    A("| Observation | Youden thr | Flags | Prevalence | AUROC | Median score, positives | Median score, negatives | Thr at percentile of negatives | Score-histogram overlap |")
    A("|---|---:|---|---:|---:|---:|---:|---:|---:|")
    for r in san.itertuples():
        A(f"| {r.observation} | {f4(r.youden_threshold)} | {r.flags} | {f3(r.prevalence)} | {f3(r.auroc)} | {f3(r.median_score_positives)} | {f3(r.median_score_negatives)} | {r.threshold_percentile_of_negatives:.0f} | {f3(r.histogram_overlap_coefficient)} |")
    A("")
    flagged = san[san["flags"] != "none"]
    A(f"Flagged by the pre-declared rules: {', '.join(f'{r.observation} ({r.flags})' for r in flagged.itertuples()) or 'none'}. No threshold is > {SANITY['high']} or near 1.")
    A("")
    A("**Explanation from the data (no threshold was altered):**")
    A("- **Low thresholds are explained by prevalence and by a compressed score scale.** The flagged classes have prevalence 1.3–3.8%. Their true positives themselves have low median scores (" + ", ".join(f"{r.observation} {f3(r.median_score_positives)}" for r in flagged.itertuples()) + "), so the best separation point lies far below 0.50. Across all classes the Youden threshold falls between percentile " + f"{san['threshold_percentile_of_negatives'].min():.0f} and {san['threshold_percentile_of_negatives'].max():.0f} of the negatives' scores.")
    A(f"- **Weak separation widens the false-positive cost.** AUROC for the flagged classes is {flagged['auroc'].min():.2f}–{flagged['auroc'].max():.2f} and their positive/negative score histograms overlap by {flagged['histogram_overlap_coefficient'].min():.2f}–{flagged['histogram_overlap_coefficient'].max():.2f}, so no threshold separates them cleanly.")
    A("- **Scores are not calibrated probabilities.** √-weighting inflates rare-class scores relative to the true rate, so absolute levels differ by class. Descriptive check (mean score over valid entries vs prevalence): " + "; ".join(f"{l} {np.mean(p[v[:, j], j]):.3f} vs {np.mean(raw[v[:, j], j] == 1):.3f}" for j, l in enumerate(LABELS) if l in ("Pleural Other", "Pneumonia", "Fracture", "Pleural Effusion", "Support Devices")) + ". No calibration has been established or attempted.")
    A("")
    A("Figure: `figures/fig8_score_distributions.png` (all 14 classes, flagged panels are labelled).")
    A("")
    A("## 9. No Finding consistency")
    A("")
    ny, n5 = nf["youden"], nf["baseline_050"]
    A(f"Abnormal = any of the 12 pathology observations (all except No Finding and Support Devices), as in the earlier project analysis. Labels were not altered and No Finding was not suppressed.")
    A("")
    A("| Quantity (validation, 28,671 images) | Youden thresholds | 0.50 | Ground-truth labels |")
    A("|---|---:|---:|---:|")
    A(f"| No Finding predicted positive | {ny['no_finding_positive']:,} ({pct(ny['no_finding_positive_pct'])}) | {n5['no_finding_positive']:,} ({pct(n5['no_finding_positive_pct'])}) | {nf['ground_truth']['no_finding_positive']:,} ({pct(nf['ground_truth']['no_finding_positive_pct'])}) |")
    A(f"| ≥ 1 abnormal finding predicted positive | {ny['abnormal_positive']:,} ({pct(ny['abnormal_positive_pct'])}) | {n5['abnormal_positive']:,} ({pct(n5['abnormal_positive_pct'])}) | n/a |")
    A(f"| **No Finding AND ≥ 1 abnormal positive (contradiction)** | **{ny['both']:,} ({pct(ny['both_pct_of_all_images'])} of all images)** | {n5['both']:,} ({pct(n5['both_pct_of_all_images'])}) | {nf['ground_truth']['gt_no_finding_with_gt_abnormal']} |")
    A(f"| Contradiction rate among No-Finding-positive images | **{pct(ny['contradiction_rate_pct_of_no_finding_positive'])}** | {pct(n5['contradiction_rate_pct_of_no_finding_positive'])} | 0.0% |")
    A(f"| Images with neither No Finding nor any abnormal finding | {ny['neither_no_finding_nor_abnormal']:,} | {n5['neither_no_finding_nor_abnormal']:,} | n/a |")
    A("")
    A("Abnormal classes most often positive together with a predicted No Finding (Youden thresholds, % of the No-Finding-positive images): " + ", ".join(f"{k} {v:.1f}%" for k, v in sorted(ny["co_occurrence_pct_of_no_finding_positive"].items(), key=lambda t: -t[1])[:6]) + ". Contradictory images carry on average " + f"{ny['mean_number_of_abnormal_positives_in_contradictions']:.2f}" + " abnormal positives.")
    A("")
    A("**Finding.** The ground-truth labels never have both. At the Youden thresholds, **No Finding is predicted positive on about three times the true rate, and ~94% of those images also have an abnormal finding predicted positive.** This is consistent with the low rare-class thresholds (the most frequent co-predicted findings are the ones with the lowest thresholds, e.g. Fracture and Lung Lesion) and with No Finding's own lowered threshold; the analysis does not isolate which factor dominates. Nothing was changed. A possible post-processing rule (for example No Finding only if no abnormal finding is positive, or precision-aware thresholds for rare classes) is **proposed only as a separate future experiment**; it is not part of C3. The downstream `consistency_warnings` already flags this case rather than hiding it.")
    A("")
    A("Figure: `figures/fig10_no_finding_cooccurrence.png`.")
    A("")
    A("**Predicted findings per image** (all 14 classes):")
    A("")
    A("| Policy | Mean predicted positives per image | Images with 0 predicted | Images with ≥ 1 | Actual explicit positives per image |")
    A("|---|---:|---:|---:|---:|")
    for k, pr in perimg.items():
        n_pos = pr.sum(axis=1)
        A(f"| {k} | {n_pos.mean():.2f} | {int((n_pos == 0).sum()):,} ({pct(100 * (n_pos == 0).mean())}) | {pct(100 * (n_pos > 0).mean())} | {actual_pos.sum(axis=1).mean():.2f} |")
    A("")
    A("## 10. Threshold stability (patient bootstrap)")
    A("")
    A(f"{N_BOOT:,} resamples, seed {BOOT_SEED}; `threshold_bootstrap.csv`, draws in `threshold_bootstrap_draws.npz`.")
    A("")
    A("| Observation | Selected | Bootstrap median | 2.5% | 97.5% | IQR | 95% width | Width / median | Flag |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|---|")
    for r in boot.itertuples():
        A(f"| {r.observation} | {f4(r.original_threshold)} | {f4(r.bootstrap_median)} | {f4(r.p2_5)} | {f4(r.p97_5)} | {f4(r.iqr)} | {f4(r.ci95_width)} | {r.ci95_width_over_median:.2f} | {'**UNSTABLE**' if r.unstable_flag else 'ok'} |")
    A("")
    uns = boot.loc[boot.unstable_flag, "observation"].tolist()
    wid = boot.sort_values("ci95_width", ascending=False)
    rel = boot.sort_values("ci95_width_over_median", ascending=False)
    A(f"- **By the pre-declared rule, unstable classes: {', '.join(uns) if uns else 'none'}.** {int(boot['original_inside_ci95'].sum())} of 14 selected thresholds lie inside their own bootstrap 95% interval; undefined resamples in total: {int(boot['n_undefined_resamples'].sum())}.")
    A(f"- **Widest absolute intervals:** {', '.join(f'{r.observation} ({r.ci95_width:.3f})' for r in wid.head(3).itertuples())}.")
    A(f"- **Widest relative to the threshold:** {', '.join(f'{r.observation} ({r.ci95_width_over_median:.2f}×)' for r in rel.head(4).itertuples())}. These are the low-threshold rare classes: the absolute width is small, but the threshold could plausibly halve or double. That is **not** flagged by the rule I fixed in advance, and I did not change the rule afterwards.")
    draws = np.load(O / "threshold_bootstrap_draws.npz")["draws"]
    below = {l: float((draws[:, j] < thr_y[j]).mean()) for j, l in enumerate(LABELS)}
    low_edge = [f"{l} ({b:.0%} of resamples below)" for l, b in below.items() if b < 0.05]
    high_edge = [f"{l} ({b:.0%} below)" for l, b in below.items() if b > 0.95]
    A("- **Position of the selected threshold within its bootstrap distribution:** at the lower edge for " + (", ".join(low_edge) or "no class") + "; at the upper edge for " + (", ".join(high_edge) or "no class") + ". Median shift (bootstrap median − selected) is largest for " + ", ".join(f"{r.observation} ({r.bootstrap_median - r.original_threshold:+.3f})" for r in boot.assign(d=(boot.bootstrap_median - boot.original_threshold).abs()).sort_values("d", ascending=False).head(3).itertuples()) + ".")
    A(f"- The 95% intervals measure sensitivity to validation-sample composition only (validation positives: {int(W['positives'].min()):,}–{int(W['positives'].max()):,} per class). They say nothing about training-seed variability or about a different data source.")
    A("")
    A("Figure: `figures/fig9_threshold_bootstrap.png`.")
    A("")
    A("## 11. Figures")
    A("")
    A("| File | Content |")
    A("|---|---|")
    for fn, d in (("fig1_youden_thresholds", "14 Youden thresholds with the 0.50 reference"),
                  ("fig2_recall_050_vs_youden", "Recall at 0.50 vs Youden, per class"),
                  ("fig3_precision_050_vs_youden", "Precision at 0.50 vs Youden, per class"),
                  ("fig4_f1_050_vs_youden", "F1 at 0.50 vs Youden, per class"),
                  ("fig5_roc_operating_points", f"ROC with operating points: {', '.join(res['representative_classes'].values())}"),
                  ("fig6_pr_operating_points", "Precision-recall curves with operating points, same classes"),
                  ("fig7_threshold_sweeps", "Sensitivity / specificity / precision / F1 vs threshold, same classes"),
                  ("fig8_score_distributions", "Score distributions by true label, all 14 classes"),
                  ("fig9_threshold_bootstrap", "Patient-bootstrap threshold intervals"),
                  ("fig10_no_finding_cooccurrence", "Abnormal findings co-predicted with No Finding")):
        A(f"| `figures/{fn}.png` (+ PDF) | {d} |")
    A("")
    A(f"Representative classes were chosen by a fixed rule (lowest, median-rank and highest validation prevalence): " + "; ".join(f"{k}: {v}" for k, v in res["representative_classes"].items()) + ".")
    A("")
    A("## 12. Limitations")
    A("")
    A("- **Thresholds are optimised on the same validation data they are evaluated on.** All threshold-dependent numbers here are **validation operating-point performance**, optimistic by construction. They are not independent test estimates.")
    A("- **The locked test split was deliberately not opened.** The task allows applying frozen thresholds to an untouched test set once. I did not, because the loss choice is still provisional (single-seed screening; multi-seed confirmation is pending). Spending the one-shot test now would leave nothing untouched for the final model. This is flagged for your decision.")
    A("- **Rare-class thresholds** rest on few validation positives (Pleural Other: " + f"{int(W.loc['Pleural Other', 'positives'])}" + ") and are low relative to their own interval; precision at those operating points is very low (§7).")
    A("- **Sigmoid scores are not calibrated probabilities.** Do not display them as percentages or compare absolute levels across classes without separate calibration work.")
    A("- **Blank labels are scored as negatives**, so some counted false positives may be findings that were present but unreported; precision is therefore a lower bound.")
    A("- **C2 loss selection is provisional**, based on one seed per arm and gaps comparable to epoch-to-epoch noise. A different final loss changes the score scale and would require re-fitting every threshold.")
    A("- **Youden ignores prevalence.** Per-class thresholds are fitted independently; no cross-class consistency is enforced (see No Finding, §9).")
    A("")
    A("## 13. Decision")
    A("")
    A("Carry the **14 validation-derived Youden J thresholds** (`thresholds_youden.json`) forward as the **provisional** operating points for the classification pipeline, as planned. The data revealed no per-class pathological edge case (every threshold is defined and inside (0, 1), and none is flagged unstable by the declared rule). The file reloads bit-exactly and the downstream per-image file is `validation_predictions_youden.csv.gz`.")
    A("")
    A("Two consequences must stay visible to downstream work:")
    A("1. The Youden operating points over-call: predicted findings per image are well above the true count, rare-class precision is 0.03–0.13, and the No Finding contradiction rate is high (§9).")
    A("2. The F1-optimal thresholds (`thresholds_f1.json`) give a markedly different, more conservative operating point. Choosing between them is a precision-vs-recall policy decision.")
    A("")
    A("Whether to adopt a prevalence- or precision-aware rule, or a No Finding consistency rule, is **not decided here** and would be a separate, approved experiment. Nothing further was started.")
    A("")
    (O / "THRESHOLD_OPTIMIZATION.md").write_text("\n".join(L), encoding="utf-8")
    print("wrote", O / "THRESHOLD_OPTIMIZATION.md", len(L), "lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
