"""Write the C4 documents from stored artifacts (numbers are read, never typed):
OPERATING_POLICY_SELECTION.md, MANUSCRIPT_C4_RESULTS.md, MANUSCRIPT_C4_METHODS.md,
FIGURE_CAPTIONS.md, TABLE_CAPTIONS.md, C4_JOURNAL_ASSET_INDEX.md

    .venv\\Scripts\\python.exe -m scripts.c4_write_docs
"""

from __future__ import annotations

import json

import pandas as pd

from scripts.compare_losses import RARE
from src.classification.labels import LABELS
from src.utils.config import PROJECT_ROOT

OUT = PROJECT_ROOT / "results/classification/experiments/c4_operating_policy"
C3 = PROJECT_ROOT / "results/classification/experiments/c3_threshold_optimization"
rd = lambda p: pd.read_csv(p, float_precision="round_trip")  # noqa: E731
f3 = lambda v: f"{v:.3f}"  # noqa: E731
wc = lambda t: len(t.split())  # noqa: E731


def main() -> int:
    comp, long = rd(OUT / "policy_comparison.csv"), rd(OUT / "policy_per_class_long.csv")
    nf, rare = rd(OUT / "no_finding_before_after.csv").set_index("policy"), rd(OUT / "rare_class_false_alarm.csv")
    counts = rd(OUT / "finding_counts_per_image.csv")
    res = json.loads((OUT / "c4_results.json").read_text(encoding="utf-8"))
    fin = json.loads((OUT / "final_operating_policy.json").read_text(encoding="utf-8"))
    chk = json.loads((OUT / "final_policy_checks.json").read_text(encoding="utf-8"))
    rep = json.loads((OUT / "c3_reproduction.json").read_text(encoding="utf-8"))
    c14 = comp[comp.scope == "14 classes"].set_index("policy")
    c13 = comp[comp.scope.str.startswith("13")].set_index("policy")
    ct = counts[counts.definition.str.startswith("13")].set_index("policy")
    ck = res["checkpoint"]
    R = {(r.observation, r.policy): r for r in rare.itertuples()}
    gt_nf = res["no_finding_ground_truth"]
    n, npat = res["n_images"], res["n_patients"]
    P = {"thr_050": "0.50", "youden": "Youden", "f1": "F1-optimal", "f1_nf": "F1-optimal + No Finding rule"}

    def rng(policy, col, fmt="{:.2f}"):
        v = [getattr(R[(c, policy)], col) for c in RARE]
        return fmt.format(min(v)) + "–" + fmt.format(max(v))

    f1_recall_up = sum(R[(c, "f1")].recall > R[(c, "thr_050")].recall for c in RARE)
    f1_prec_down = sum(R[(c, "f1")].precision < R[(c, "thr_050")].precision for c in RARE)
    raw, rule, strict = nf.loc["f1"], nf.loc["f1_nf"], nf.loc["f1_nf_strict"]
    gt_nf_pct = 100 * gt_nf["gt_no_finding_positive"] / n
    cl = lambda k, m: c14.loc[k, f"macro_{m}"]  # noqa: E731

    # ------------------------------------------------------------------ Table-1 markdown for the report
    t1 = (OUT / "tables/table1_policy_comparison.md").read_text(encoding="utf-8")
    t1b = (OUT / "tables/table1b_policy_comparison_13_abnormal.md").read_text(encoding="utf-8")
    t2 = (OUT / "tables/table2_final_per_class_operating_points.md").read_text(encoding="utf-8")
    t3 = (OUT / "tables/table3_rare_class_performance.md").read_text(encoding="utf-8")
    t4 = (OUT / "tables/table4_no_finding_consistency.md").read_text(encoding="utf-8")

    # ================================================================== OPERATING_POLICY_SELECTION.md
    L = []
    A = L.append
    A("# C4: final operating-policy selection and No Finding consistency")
    A("")
    A("_Generated by `scripts/c4_write_docs.py` from the stored C4 artifacts. Validation data only. The locked test split was not opened; no model was trained, no inference was rerun and no bootstrap was repeated._")
    A("")
    A("## 1. Experiment objective")
    A("")
    A("C2 compared score-based ranking; C3 produced two candidate threshold sets. C4 decides which **binary operating policy** should feed the downstream retrieval and report-generation stages, taking into account not only per-class accuracy but also how many findings are passed on per image and whether the final binary output is logically consistent.")
    A("")
    A("## 2. Model and dataset")
    A("")
    A(f"- **Model:** DenseNet-121, 14 independent sigmoid outputs (multi-label); loss = √-weighted BCE (C2-B, provisional). Checkpoint `{ck['path']}`, SHA-256 `{ck['sha256_recomputed']}`, epoch {ck['selected_epoch']}.")
    A(f"- **Data:** {n:,} frontal CheXpert validation images from {npat:,} patients; 14 observations in the fixed order of the project; uncertain entries are excluded from every metric and blank entries are scored negative.")
    A(f"- **C3 reproduction:** counts identical and metrics within 1e-12 for all three C3 policies; scores and Youden predictions in the C3 per-image file are bit-identical ({rep['reproduced']}).")
    A("- **Terminology:** outputs are *sigmoid scores* (model scores); they are not calibrated probabilities.")
    A("")
    A("## 3. Compared operating policies")
    A("")
    A("1. **Threshold 0.50** for every class.")
    A("2. **Youden J** per-class thresholds (C3).")
    A("3. **F1-optimal** per-class thresholds (C3).")
    A("4. **F1-optimal + No Finding consistency rule:** No Finding is positive only if its own score exceeds its threshold **and** none of the 12 pathology observations is positive. Only the final binary No Finding output can change; scores and all other predictions are untouched.")
    A("")
    A("Definitions used throughout: *pathology* = the 12 observations other than No Finding and Support Devices (used by the rule and the contradiction rate; Support Devices is excluded because the source labels allow No Finding together with a device: "
      f"{gt_nf['gt_no_finding_with_support_devices']:,} of {gt_nf['gt_no_finding_positive']:,} validation No Finding images also have Support Devices positive); *abnormal findings* = all 13 observations other than No Finding (used for finding counts and the 13-class macro).")
    A("")
    A("## 4. Evaluation metrics")
    A("")
    A("Precision = TP/(TP+FP); recall = TP/(TP+FN); specificity = TN/(TN+FP); F1 = 2TP/(2TP+FP+FN); balanced accuracy = (recall + specificity)/2. Macro values are unweighted means over classes. A positive prediction is `score ≥ threshold`. FP per TP = FP/TP.")
    A("")
    A("## 5. Overall results")
    A("")
    A("**Table 1. Macro average over all 14 observations.**")
    A("")
    A(t1)
    A("**Table 1b. Macro average over the 13 abnormal findings only** (the No Finding rule changes one label, so this isolates classifier-wide effects).")
    A("")
    A(t1b)
    A(f"The No Finding rule leaves all 13 abnormal-class predictions unchanged (identical columns: {res['rule']['abnormal_columns_identical']}); it altered the No Finding output on {res['rule']['images_changed']:,} images. The difference between policies 3 and 4 in the 14-class macro therefore comes from No Finding alone (macro F1 {cl('f1', 'f1'):.4f} → {cl('f1_nf', 'f1'):.4f}).")
    A("")
    A("### Finding-count behaviour (13 abnormal observations per image)")
    A("")
    A("| Source | Mean | Median | P25 | P75 | P95 | Max | 0 findings | 1 | 2–3 | 4–5 | > 5 |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for k, nm in (("ground_truth", "Ground truth"), ("thr_050", "0.50"), ("youden", "Youden J"), ("f1", "F1-optimal")):
        r = ct.loc[k]
        A(f"| {nm} | {r['mean']:.2f} | {r['median']:.0f} | {r['p25']:.0f} | {r['p75']:.0f} | {r['p95']:.0f} | {int(r['max'])} | {r.pct_0:.1f}% | {r.pct_1:.1f}% | {r.pct_2_3:.1f}% | {r.pct_4_5:.1f}% | {r.pct_gt5:.1f}% |")
    A("")
    A(f"Ground truth averages {ct.loc['ground_truth', 'mean']:.2f} positive findings per image. The 0.50 policy is closest ({ct.loc['thr_050', 'mean']:.2f}); F1-optimal passes on {ct.loc['f1', 'mean']:.2f}; Youden passes on {ct.loc['youden', 'mean']:.2f}, with {ct.loc['youden', 'pct_gt5']:.1f}% of images carrying more than five findings (ground truth: {ct.loc['ground_truth', 'pct_gt5']:.1f}%). The rule does not change these counts (No Finding is not counted).")
    A("")
    A("## 6. Per-class analysis")
    A("")
    A("The full per-class F1-optimal table is `f1_operating_table.csv`; all policies are in `policy_per_class_long.csv`. Figure 4 compares per-class F1 and Figure 5 the precision-recall movement.")
    A("")
    fl = long[long.policy == "f1"].set_index("observation")
    yl = long[long.policy == "youden"].set_index("observation")
    bl = long[long.policy == "thr_050"].set_index("observation")
    better = [c for c in LABELS if fl.loc[c, "f1"] > bl.loc[c, "f1"]]
    A(f"- F1-optimal thresholds give a higher per-class F1 than 0.50 in {len(better)} of 14 classes and than Youden in {sum(fl.loc[c, 'f1'] > yl.loc[c, 'f1'] for c in LABELS)} of 14.")
    A(f"- Youden has the highest recall in {sum(yl.loc[c, 'recall'] >= max(fl.loc[c, 'recall'], bl.loc[c, 'recall']) for c in LABELS)} of 14 classes, with the lowest precision in {sum(yl.loc[c, 'precision'] <= min(fl.loc[c, 'precision'], bl.loc[c, 'precision']) for c in LABELS)} of 14.")
    spread = pd.DataFrame({"obs": list(LABELS), "rng": [max(fl.loc[c, "recall"], yl.loc[c, "recall"], bl.loc[c, "recall"]) - min(fl.loc[c, "recall"], yl.loc[c, "recall"], bl.loc[c, "recall"]) for c in LABELS]}).sort_values("rng")
    A("- Recall spread across the three policies is smallest for " + ", ".join(f"{r.obs} ({r.rng:.2f})" for r in spread.head(3).itertuples()) + " and largest for " + ", ".join(f"{r.obs} ({r.rng:.2f})" for r in spread.tail(3).iloc[::-1].itertuples()) + ".")
    A("")
    A("**Table 2. Final per-class operating points.**")
    A("")
    A(t2)
    A("## 7. Rare-class behaviour")
    A("")
    A("**Table 3. Rare-class false-alarm burden.**")
    A("")
    A(t3)
    A(f"- **0.50:** recall {rng('thr_050', 'recall')}, precision {rng('thr_050', 'precision')}, {rng('thr_050', 'fp_per_tp', '{:.1f}')} false positives per true positive.")
    A(f"- **Youden:** recall {rng('youden', 'recall')} but precision {rng('youden', 'precision')} and {rng('youden', 'fp_per_tp', '{:.1f}')} false positives per true positive (Pleural Other: {R[('Pleural Other', 'youden')].fp_per_tp:.1f}).")
    A(f"- **F1-optimal:** recall {rng('f1', 'recall')} (higher than 0.50 in {f1_recall_up} of 6), precision {rng('f1', 'precision')} (lower than 0.50 in {f1_prec_down} of 6), {rng('f1', 'fp_per_tp', '{:.1f}')} false positives per true positive.")
    A("- **No policy makes rare-class output precise:** under F1-optimal thresholds the best rare-class precision is "
      f"{max(R[(c, 'f1')].precision for c in RARE):.2f}, so most positive calls for these classes are false alarms. This is a limitation of the classifier, not of the thresholding rule.")
    A("")
    A("## 8. No Finding consistency")
    A("")
    A("**Table 4. No Finding before and after the rule (F1-optimal thresholds).**")
    A("")
    A(t4)
    A(f"- **Problem:** with F1-optimal thresholds No Finding is positive together with at least one pathology on {raw.contradiction_pct_of_all_images_pathology12:.1f}% of images ({int(raw.contradiction_n_pathology12):,}; {raw.contradiction_pct_of_no_finding_positive_pathology12:.1f}% of images predicted No Finding). The same quantity is {nf.loc['thr_050', 'contradiction_pct_of_all_images_pathology12']:.1f}% at 0.50 and {nf.loc['youden', 'contradiction_pct_of_all_images_pathology12']:.1f}% under Youden. The validation labels contain {gt_nf['gt_contradiction_pathology12']} such cases.")
    A(f"- **Effect of the rule:** contradictions fall to {rule.contradiction_pct_of_all_images_pathology12:.1f}%. No Finding precision rises {raw.precision:.3f} → {rule.precision:.3f}, specificity {raw.specificity:.3f} → {rule.specificity:.3f}; recall falls {raw.recall:.3f} → {rule.recall:.3f} and F1 {raw.f1:.3f} → {rule.f1:.3f}. The images predicted No Finding drop from {raw.pct_predicted_no_finding:.1f}% to {rule.pct_predicted_no_finding:.1f}% (label prevalence {gt_nf_pct:.1f}%).")
    A(f"- **Sensitivity analysis:** also suppressing No Finding when Support Devices is positive would remove all contradictions under the broader definition, but No Finding recall would fall to {strict.recall:.3f} (F1 {strict.f1:.3f}), because devices are common alongside truly normal findings. The narrower pathology definition is therefore used. Under the broader definition the selected policy still has {rule.contradiction_pct_of_all_images_incl_support_devices:.1f}% images with No Finding and Support Devices both positive, which the labels also permit.")
    A("")
    A("## 9. Downstream implications")
    A("")
    A("The retrieval query is built from the positive findings, so every false-positive finding becomes query content and can pull in reports about conditions the image does not show. Youden's thresholds would pass on a mean of "
      f"{ct.loc['youden', 'mean']:.1f} findings per image against {ct.loc['ground_truth', 'mean']:.1f} in the labels, with {ct.loc['youden', 'pct_gt5']:.0f}% of images above five, and {R[('Pleural Other', 'youden')].fp_per_tp:.0f} false alarms per correct call for the rarest class. The F1-optimal policy passes on {ct.loc['f1', 'mean']:.1f}. A logically consistent No Finding output also avoids sending the retrieval and generation stages a statement of normality together with listed abnormalities. These are mechanisms inferred from the counts above; the effect on retrieval quality and report content has not been measured.")
    A("")
    A("## 10. Final operating policy")
    A("")
    A("**Selected: F1-optimal per-class thresholds + the No Finding consistency rule** (`final_operating_policy.json`). The criteria were weighed qualitatively, without a composite score:")
    A("")
    A("| Criterion | 0.50 | Youden | F1-optimal | F1 + NF rule |")
    A("|---|---|---|---|---|")
    A(f"| A. Macro F1 (14 / 13 classes) | {cl('thr_050', 'f1'):.3f} / {c13.loc['thr_050', 'macro_f1']:.3f} | {cl('youden', 'f1'):.3f} / {c13.loc['youden', 'macro_f1']:.3f} | **{cl('f1', 'f1'):.3f}** / **{c13.loc['f1', 'macro_f1']:.3f}** | {cl('f1_nf', 'f1'):.3f} / {c13.loc['f1_nf', 'macro_f1']:.3f} |")
    A(f"| B. Macro precision | **{cl('thr_050', 'precision'):.3f}** | {cl('youden', 'precision'):.3f} | {cl('f1', 'precision'):.3f} | {cl('f1_nf', 'precision'):.3f} |")
    A(f"| C. Macro recall | {cl('thr_050', 'recall'):.3f} | **{cl('youden', 'recall'):.3f}** | {cl('f1', 'recall'):.3f} | {cl('f1_nf', 'recall'):.3f} |")
    A(f"| D. Rare-class false positives per TP | {rng('thr_050', 'fp_per_tp', '{:.1f}')} | {rng('youden', 'fp_per_tp', '{:.1f}')} | {rng('f1', 'fp_per_tp', '{:.1f}')} | {rng('f1', 'fp_per_tp', '{:.1f}')} |")
    A(f"| E. Mean findings/image (truth {ct.loc['ground_truth', 'mean']:.2f}) | **{ct.loc['thr_050', 'mean']:.2f}** | {ct.loc['youden', 'mean']:.2f} | {ct.loc['f1', 'mean']:.2f} | {ct.loc['f1', 'mean']:.2f} |")
    A(f"| F. No Finding contradiction (% of images) | {nf.loc['thr_050', 'contradiction_pct_of_all_images_pathology12']:.1f} | {nf.loc['youden', 'contradiction_pct_of_all_images_pathology12']:.1f} | {raw.contradiction_pct_of_all_images_pathology12:.1f} | **0.0** |")
    A("")
    A(f"- **Youden is rejected** for downstream use: it has the highest recall but the lowest precision and macro F1, {ct.loc['youden', 'mean']:.1f} findings per image, and the largest rare-class and No Finding contradiction burden.")
    A(f"- **0.50 is not selected** although it has the best macro precision and the finding count closest to the labels: its recall is {cl('thr_050', 'recall'):.2f}, and for the rare classes {rng('thr_050', 'recall')}, so most true rare findings never reach retrieval.")
    A(f"- **F1-optimal + rule is selected** as the most balanced policy that also satisfies the consistency requirement: macro F1 {cl('f1_nf', 'f1'):.3f} (vs {cl('thr_050', 'f1'):.3f} at 0.50), macro recall {cl('f1_nf', 'recall'):.3f} (vs {cl('thr_050', 'recall'):.3f}), macro precision {cl('f1_nf', 'precision'):.3f} (vs {cl('thr_050', 'precision'):.3f}), zero contradictions. Raw F1-optimal has a marginally higher macro F1 ({cl('f1', 'f1'):.4f} vs {cl('f1_nf', 'f1'):.4f}) but {raw.contradiction_pct_of_all_images_pathology12:.1f}% contradictory images; the cost of the rule falls entirely on No Finding (recall {raw.recall:.3f} → {rule.recall:.3f}, F1 {raw.f1:.3f} → {rule.f1:.3f}).")
    A("- **What the choice does not achieve:** the policy still passes on about one more finding per image than the labels contain, and rare-class precision remains low (§7). It is a validation-set operating point, to be revisited if the loss, the model or the score calibration changes.")
    A("")
    A(f"Final-policy file checks: scores bit-identical to C2-B ({chk['scores_bit_identical_to_c2b']}), raw predictions equal the threshold rule ({chk['raw_preds_equal_threshold_rule']}), final predictions equal the rule applied to raw ({chk['final_preds_equal_rule_applied_to_raw']}), only No Finding differs between raw and final ({chk['only_no_finding_differs_between_raw_and_final']}). Figure 8 shows the final thresholds.")
    A("")
    A("## 11. Limitations")
    A("")
    A("- Thresholds were selected on the same validation data used to evaluate them, so threshold-dependent numbers are validation operating-point performance, not independent estimates.")
    A("- The locked test split has not been evaluated; it remains untouched until the whole classifier configuration is frozen.")
    A("- Sigmoid scores have not been calibrated; absolute score levels differ between classes.")
    A("- The loss (√-weighted BCE) was chosen provisionally from a single-seed screening study; a different final loss requires re-fitting all thresholds.")
    A("- Blank labels are scored as negative, so precision may understate true precision for findings that were present but not reported.")
    A("- The effect on retrieval quality and generated reports has not been measured.")
    A("- The No Finding rule trades No Finding recall for consistency; whether that is the right trade for report generation is untested.")
    A("")
    A("## 12. Conclusion")
    A("")
    A(f"On the validation set, F1-optimal per-class thresholds with a deterministic No Finding consistency rule gave a more balanced precision-recall trade-off than either the fixed 0.50 threshold or Youden's J (macro F1 {cl('f1_nf', 'f1'):.3f}, recall {cl('f1_nf', 'recall'):.3f}, precision {cl('f1_nf', 'precision'):.3f}), passed on {ct.loc['f1', 'mean']:.2f} findings per image, and removed No Finding contradictions. Rare-class precision remains low under every policy.")
    A("")
    (OUT / "OPERATING_POLICY_SELECTION.md").write_text("\n".join(L), encoding="utf-8")

    # ================================================================== manuscript Methods
    methods = f"""# Methods: operating-policy selection (C4)

## Threshold policies

Operating points were derived from the sigmoid output scores of the selected DenseNet-121 classifier (14 independent outputs, one per CheXpert observation; √-weighted binary cross-entropy training). Scores were not normalised across classes, and they are treated as model scores rather than calibrated probabilities. A finding was called positive when its score was greater than or equal to a class-specific threshold. Four policies were compared: (i) a fixed threshold of 0.50 for every class; (ii) Youden's J thresholds, which maximise sensitivity + specificity − 1 for each class; (iii) F1-optimal thresholds, which maximise the F1 score for each class; and (iv) the F1-optimal thresholds combined with a No Finding consistency rule. Candidate thresholds were the distinct validation scores of each class. Exact ties were resolved deterministically (Youden: higher sensitivity, then higher threshold; F1: higher recall, then higher threshold).

## No Finding consistency rule

Because No Finding is not logically compatible with a pathological finding, the rule set the final No Finding output to negative whenever at least one of the twelve pathology observations (all observations except No Finding and Support Devices) was predicted positive; otherwise No Finding remained positive only if its own score exceeded its threshold. Support Devices was excluded from the rule because the reference labels permit No Finding together with a device ({gt_nf['gt_no_finding_with_support_devices']:,} of {gt_nf['gt_no_finding_positive']:,} validation No Finding images also had Support Devices positive). The rule altered only the final binary No Finding output; scores and all other predictions were unchanged.

## Evaluation procedure

All analyses used the {n:,} frontal images of the {npat:,} patients in the validation partition, with predictions generated once under a fixed single-precision evaluation policy and reused without further inference. Uncertain reference labels were excluded from every metric and blank labels were treated as negative. For each class and policy we computed precision, recall, specificity, F1 and balanced accuracy from the confusion counts, and report unweighted macro averages over all 14 observations and over the 13 observations other than No Finding. Undefined values were not replaced by zero. The number of positive findings per image was computed over the 13 observations other than No Finding and compared with the number of positive reference labels. Rare-class behaviour was examined for six classes defined in advance in the loss-comparison study, using false positives per true positive. The No Finding contradiction rate was defined as the percentage of images with No Finding and at least one pathology observation both positive. Before the analysis, the previously reported threshold-dependent metrics were reproduced from the stored scores and thresholds.

## Policy selection and test-set handling

Policies were compared qualitatively on macro F1, precision, recall, rare-class false-alarm burden, findings per image and logical consistency, without a composite score. Thresholds and the final policy were selected using the validation partition only. The held-out test partition was not used at any stage of threshold or policy selection and remained unevaluated, so that it can serve as an untouched final evaluation once the complete classifier configuration, including the loss function and score calibration, has been fixed. Threshold-dependent results reported here therefore describe validation operating-point performance and are optimistic by construction.
"""
    mw = wc(methods)
    (OUT / "MANUSCRIPT_C4_METHODS.md").write_text(methods, encoding="utf-8")

    # ================================================================== manuscript Results
    results = f"""# Results: operating-policy selection (C4)

## Operating-point selection

On the validation set ({n:,} images, {npat:,} patients), the choice of threshold policy changed the precision-recall balance substantially while the underlying scores were identical. A fixed threshold of 0.50 gave a macro precision of {cl('thr_050', 'precision'):.3f}, macro recall of {cl('thr_050', 'recall'):.3f} and macro F1 of {cl('thr_050', 'f1'):.3f} across the 14 observations (Figure 1, Table 1). Class-specific Youden thresholds increased macro recall to {cl('youden', 'recall'):.3f} and balanced accuracy from {cl('thr_050', 'balanced_accuracy'):.3f} to {cl('youden', 'balanced_accuracy'):.3f}, but reduced macro precision to {cl('youden', 'precision'):.3f}, macro specificity from {cl('thr_050', 'specificity'):.3f} to {cl('youden', 'specificity'):.3f} and macro F1 to {cl('youden', 'f1'):.3f} (Figure 2). F1-optimal thresholds provided an intermediate operating point, with macro precision {cl('f1', 'precision'):.3f}, recall {cl('f1', 'recall'):.3f} and the highest macro F1 ({cl('f1', 'f1'):.3f}).

The policies also differed in how many findings they would pass to downstream stages (Figure 3). The reference labels contained a mean of {ct.loc['ground_truth', 'mean']:.2f} positive findings per image among the 13 observations other than No Finding. The 0.50 policy predicted {ct.loc['thr_050', 'mean']:.2f}, the F1-optimal policy {ct.loc['f1', 'mean']:.2f} and the Youden policy {ct.loc['youden', 'mean']:.2f}; {ct.loc['youden', 'pct_gt5']:.1f}% of images received more than five findings under Youden thresholds, compared with {ct.loc['f1', 'pct_gt5']:.1f}% under F1-optimal thresholds and {ct.loc['ground_truth', 'pct_gt5']:.1f}% in the reference labels. At the per-class level, F1-optimal thresholds produced a higher F1 than the 0.50 threshold in {len(better)} of 14 observations (Figure 4), and the movement from 0.50 to Youden to F1-optimal thresholds traced a precision-recall trade-off in most classes (Figure 5).

## Rare-class performance

Differences between policies were largest for the six low-prevalence observations (Table 3, Figure 6). At a threshold of 0.50, recall for these classes ranged from {rng('thr_050', 'recall')}. Youden thresholds increased recall to {rng('youden', 'recall')}, at the cost of precision of {rng('youden', 'precision')} and {rng('youden', 'fp_per_tp', '{:.1f}')} false positives per true positive; for Pleural Other, the rarest class, this corresponded to {R[('Pleural Other', 'youden')].fp_per_tp:.1f} false positives per true positive. F1-optimal thresholds gave recall of {rng('f1', 'recall')} and precision of {rng('f1', 'precision')}, with {rng('f1', 'fp_per_tp', '{:.1f}')} false positives per true positive. Compared with the 0.50 threshold, F1-optimal thresholds increased recall in {f1_recall_up} of the six classes and lowered precision in {f1_prec_down}. Even under the most favourable policy, no rare class exceeded a precision of {max(R[(c, 'f1')].precision for c in RARE):.2f}, so most positive predictions for these observations were false positives on the validation set.

## No Finding consistency

With F1-optimal thresholds, No Finding and at least one pathology observation were predicted positive together on {raw.contradiction_pct_of_all_images_pathology12:.1f}% of images ({raw.contradiction_pct_of_no_finding_positive_pathology12:.1f}% of images predicted No Finding), compared with {nf.loc['thr_050', 'contradiction_pct_of_all_images_pathology12']:.1f}% at 0.50 and {nf.loc['youden', 'contradiction_pct_of_all_images_pathology12']:.1f}% with Youden thresholds; the reference labels contained none (Figure 7, Table 4). The deterministic consistency rule changed the No Finding output on {res['rule']['images_changed']:,} images and removed all contradictions. It increased No Finding precision from {raw.precision:.3f} to {rule.precision:.3f} and specificity from {raw.specificity:.3f} to {rule.specificity:.3f}, while recall decreased from {raw.recall:.3f} to {rule.recall:.3f} and F1 from {raw.f1:.3f} to {rule.f1:.3f}. Predictions for the 13 abnormal observations were unchanged, so macro metrics over those observations were identical with and without the rule. Treating Support Devices as an abnormal finding in the rule reduced No Finding recall to {strict.recall:.3f}.

## Final policy selection

F1-optimal per-class thresholds combined with the No Finding consistency rule were selected as the operating policy for downstream use (Figure 8, Table 2). Relative to the 0.50 threshold, this policy provided higher macro recall ({cl('f1_nf', 'recall'):.3f} vs {cl('thr_050', 'recall'):.3f}) and macro F1 ({cl('f1_nf', 'f1'):.3f} vs {cl('thr_050', 'f1'):.3f}) at a lower macro precision ({cl('f1_nf', 'precision'):.3f} vs {cl('thr_050', 'precision'):.3f}), and relative to Youden thresholds it passed on {ct.loc['youden', 'mean'] - ct.loc['f1', 'mean']:.1f} fewer findings per image. It predicted {ct.loc['f1', 'mean']:.2f} findings per image on average, still above the {ct.loc['ground_truth', 'mean']:.2f} in the reference labels, and rare-class precision remained low. These results describe validation operating-point performance: thresholds were optimised on the same data, the held-out test partition has not been evaluated, and the model scores have not been calibrated.
"""
    rw = wc(results)
    (OUT / "MANUSCRIPT_C4_RESULTS.md").write_text(results, encoding="utf-8")
    assert 600 <= rw <= 900 and 350 <= mw <= 600, (rw, mw)

    # ================================================================== captions
    fc = f"""# Figure captions (C4)

All figures: CheXpert validation partition ({n:,} frontal images, {npat:,} patients); uncertain labels excluded, blank labels scored negative; sigmoid output scores of a DenseNet-121 trained with √-weighted binary cross-entropy. Thresholds were selected on this same partition.

**Figure 1. Macro precision, recall and F1 under four operating policies.** Fixed threshold 0.50, Youden J thresholds, F1-optimal thresholds, and F1-optimal thresholds with the No Finding consistency rule are compared (macro average over 14 observations). Youden thresholds gave the highest recall ({cl('youden', 'recall'):.2f}) and the lowest precision ({cl('youden', 'precision'):.2f}); F1-optimal thresholds gave the highest macro F1 ({cl('f1', 'f1'):.2f}) with intermediate recall ({cl('f1', 'recall'):.2f}) and precision ({cl('f1', 'precision'):.2f}).

**Figure 2. Macro specificity and balanced accuracy under four operating policies.** Same policies and averaging as Figure 1. Youden thresholds had the highest balanced accuracy ({cl('youden', 'balanced_accuracy'):.2f}) and the lowest specificity ({cl('youden', 'specificity'):.2f}).

**Figure 3. Number of positive findings per image.** Share of validation images with 0 to 10+ positive findings among the 13 observations other than No Finding, for the reference labels (mean {ct.loc['ground_truth', 'mean']:.2f}), the 0.50 policy ({ct.loc['thr_050', 'mean']:.2f}), Youden thresholds ({ct.loc['youden', 'mean']:.2f}) and F1-optimal thresholds ({ct.loc['f1', 'mean']:.2f}). Youden thresholds shifted the distribution toward more than five findings per image ({ct.loc['youden', 'pct_gt5']:.1f}% of images).

**Figure 4. Per-class F1 under three thresholding policies.** F1 for each of the 14 observations at the 0.50 threshold, Youden J thresholds and F1-optimal thresholds. Lines connect the three values for each class.

**Figure 5. Precision-recall operating points per class.** For each observation, the operating point moves from the 0.50 threshold to the Youden threshold to the F1-optimal threshold. Youden thresholds moved points toward higher recall and lower precision in most classes.

**Figure 6. Rare-class false-alarm burden.** Precision, recall and false positives per true positive for the six rare observations under the 0.50, Youden and F1-optimal policies. Youden thresholds raised recall to {rng('youden', 'recall')} but required {rng('youden', 'fp_per_tp', '{:.1f}')} false positives per true positive; F1-optimal thresholds required {rng('f1', 'fp_per_tp', '{:.1f}')}.

**Figure 7. No Finding before and after the consistency rule.** Left: No Finding precision, recall, specificity and F1 for F1-optimal thresholds with and without the rule. Right: percentage of images with No Finding and a pathology observation predicted positive together (of all images, and of images predicted No Finding). The rule removed all contradictions ({raw.contradiction_pct_of_all_images_pathology12:.1f}% to {rule.contradiction_pct_of_all_images_pathology12:.1f}% of images) and reduced No Finding recall from {raw.recall:.2f} to {rule.recall:.2f}.

**Figure 8. Final per-class thresholds.** Selected F1-optimal thresholds on the sigmoid score for the 14 observations; the vertical line marks the conventional 0.50 threshold.
"""
    (OUT / "FIGURE_CAPTIONS.md").write_text(fc, encoding="utf-8")
    tc = f"""# Table captions (C4)

**Table 1. Operating-policy comparison (14 observations).** Macro precision, recall, specificity, F1, balanced accuracy, mean predicted findings per image (13 observations other than No Finding) and No Finding contradiction rate (% of images with No Finding and a pathology observation both positive) for the four policies, on the validation partition.

**Table 1b. Operating-policy comparison (13 abnormal observations).** As Table 1, averaged over the 13 observations other than No Finding. The No Finding rule does not affect these values.

**Table 2. Final per-class operating points.** Prevalence, final threshold, precision, recall, specificity, F1 and balanced accuracy for each observation under the selected policy (F1-optimal thresholds with No Finding consistency rule), on the validation partition. Thresholds were selected on the same partition.

**Table 3. Rare-class performance.** Threshold, true positives (TP), false positives (FP), precision, recall, F1 and false positives per true positive for the six rare observations under the 0.50, Youden and F1-optimal policies.

**Table 4. No Finding consistency analysis.** Confusion counts and metrics for No Finding, the percentage of images predicted No Finding, and the contradiction rate before and after the consistency rule. The reference labels contain {gt_nf['gt_contradiction_pathology12']} contradictory images.
"""
    (OUT / "TABLE_CAPTIONS.md").write_text(tc, encoding="utf-8")

    idx = """# C4 journal asset index

| Asset | File | What it demonstrates | Suggested manuscript section |
|---|---|---|---|
| Figure 1 | `figures/fig1_policy_precision_recall_f1.{png,pdf,svg}` | Macro precision/recall/F1 trade-off across policies | Results |
| Figure 2 | `figures/fig2_policy_specificity_balanced_accuracy.{png,pdf,svg}` | Specificity and balanced accuracy by policy | Results |
| Figure 3 | `figures/fig3_predicted_findings_per_image.{png,pdf,svg}` | Over-prediction of findings per image by policy | Results / Discussion |
| Figure 4 | `figures/fig4_per_class_f1.{png,pdf,svg}` | Per-class F1 under three policies | Results / Supplementary |
| Figure 5 | `figures/fig5_per_class_precision_recall_tradeoff.{png,pdf,svg}` | Per-class movement along the precision-recall trade-off | Results / Supplementary |
| Figure 6 | `figures/fig6_rare_class_false_alarm_burden.{png,pdf,svg}` | Rare-class precision, recall and false-alarm burden | Results / Discussion |
| Figure 7 | `figures/fig7_no_finding_consistency.{png,pdf,svg}` | Effect of the No Finding rule | Results |
| Figure 8 | `figures/fig8_final_thresholds.{png,pdf,svg}` | Final per-class thresholds | Results / Supplementary |
| Table 1 | `tables/table1_policy_comparison.{csv,md,tex}` | Overall four-policy comparison (14 classes) | Results |
| Table 1b | `tables/table1b_policy_comparison_13_abnormal.{csv,md,tex}` | Same, 13 abnormal observations only | Results / Supplementary |
| Table 2 | `tables/table2_final_per_class_operating_points.{csv,md,tex}` | Final class-specific thresholds and metrics | Results / Supplementary |
| Table 3 | `tables/table3_rare_class_performance.{csv,md,tex}` | Rare-class false-alarm burden | Results / Discussion |
| Table 4 | `tables/table4_no_finding_consistency.{csv,md,tex}` | No Finding before/after the rule | Results |
| Captions | `FIGURE_CAPTIONS.md`, `TABLE_CAPTIONS.md` | Manuscript-ready captions | All |
| Prose | `MANUSCRIPT_C4_METHODS.md`, `MANUSCRIPT_C4_RESULTS.md` | Draft Methods and Results text | Methods / Results |
| Policy | `final_operating_policy.json` | Machine-readable selected policy | Supplementary / code release |
| Predictions | `validation_predictions_final_policy.csv.gz` | Per-image scores, thresholds, raw and final predictions | Supplementary / reproducibility |
| Figure data | `figures/source_data/*.csv` | Exact numbers plotted in each figure | Supplementary |
"""
    (OUT / "C4_JOURNAL_ASSET_INDEX.md").write_text(idx, encoding="utf-8")
    print(json.dumps({"results_words": rw, "methods_words": mw}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
