"""Write the C5 documents from stored artifacts (numbers are read, never typed):
CALIBRATION_ANALYSIS.md, MANUSCRIPT_C5_METHODS.md, MANUSCRIPT_C5_RESULTS.md, FIGURE_CAPTIONS.md,
TABLE_CAPTIONS.md, C5_JOURNAL_ASSET_INDEX.md

    .venv\\Scripts\\python.exe -m scripts.c5_write_docs
"""

from __future__ import annotations

import json

import pandas as pd

from src.classification.labels import LABELS
from src.utils.config import PROJECT_ROOT

OUT = PROJECT_ROOT / "results/classification/experiments/c5_calibration"
rd = lambda n: pd.read_csv(OUT / n, float_precision="round_trip")  # noqa: E731
f3, f4 = (lambda v: f"{v:.3f}"), (lambda v: f"{v:.4f}")  # noqa: E731
wc = lambda t: len(t.split())  # noqa: E731


def main() -> int:
    sel = rd("raw_vs_selected_per_class.csv").set_index("observation")
    mac = rd("method_comparison_macro.csv").set_index("method")
    mp = rd("threshold_mapping.csv")
    rk = rd("ranking_sanity.csv")
    cvl = rd("cv_fit_log.csv")
    gu = rd("calibrator_guardrails.csv")
    msel = rd("method_selection.csv").set_index("observation")
    res = json.loads((OUT / "c5_results.json").read_text(encoding="utf-8"))
    cal = json.loads((OUT / "final_calibrators.json").read_text(encoding="utf-8"))
    rep = json.loads((OUT / "c4_reproduction.json").read_text(encoding="utf-8"))
    lg = res["logit_reconstruction"]
    cv = res["cv"]
    n, npat = res["n_images"], res["n_patients"]
    ck = res["checkpoint"]
    sel["d_brier"] = 100 * (sel.calibrated_brier / sel.raw_brier - 1)
    sel["d_ll"] = 100 * (sel.calibrated_log_loss / sel.raw_log_loss - 1)
    top = sel.sort_values("d_brier").head(4)
    low = sel.sort_values("d_brier", ascending=False).head(4)
    M = lambda m, k: mac.loc[m, k]  # noqa: E731
    pct = lambda a, b: 100 * (b / a - 1)  # noqa: E731
    platt = {l: cal["classes"][l] for l in LABELS}
    a_rng = (min(v["a"] for v in platt.values()), max(v["a"] for v in platt.values()))
    b_rng = (min(v["b"] for v in platt.values()), max(v["b"] for v in platt.values()))
    mean_gap_raw = (sel.raw_mean_score / sel.prevalence)
    mean_gap_cal = (sel.calibrated_oof_mean - sel.prevalence).abs()
    pl = cvl[cvl.method == "platt"].groupby("observation")["a"].agg(["min", "max"])
    fold_spread = (pl["max"] - pl["min"]).max()
    oof_auroc_dev = (rk.calibrated_oof_auroc - rk.raw_auroc).abs().max()
    fin_auroc_dev = (rk.calibrated_final_auroc - rk.raw_auroc).abs().max()
    fin_auprc_dev = (rk.calibrated_final_auprc - rk.raw_auprc).abs().max()
    flagged = {k: v for k, v in res["guardrail_flags"].items()}
    uni = res["uniform_check"]
    per_class_counts = msel["per_class_selected"].value_counts().to_dict()
    cal_thr_rng = (mp.calibrated_equivalent_threshold.min(), mp.calibrated_equivalent_threshold.max())
    rb = rd("reliability_bins.csv")
    rel = {}
    for (c, sr), g in rb.groupby(["observation", "series"]):
        rel[(c, sr)] = (int((g.observed_fraction < g.mean_predicted).sum()), len(g), float((g.observed_fraction - g.mean_predicted).abs().max()))
    n_over = int((sel.raw_mean_score > sel.prevalence).sum())
    not_over = ", ".join(sel.index[sel.raw_mean_score <= sel.prevalence])
    RC = ("Pleural Other", "Pneumothorax", "Support Devices")
    rel_txt = "; ".join(f"{c}: raw observed fraction below the mean prediction in {rel[(c, 'raw')][0]} of {rel[(c, 'raw')][1]} bins (largest gap {rel[(c, 'raw')][2]:.3f}), calibrated largest gap {rel[(c, 'calibrated_oof')][2]:.3f}" for c in RC)
    t1 = (OUT / "tables/table1_calibration_method_comparison.md").read_text(encoding="utf-8")
    t2 = (OUT / "tables/table2_per_class_raw_vs_calibrated.md").read_text(encoding="utf-8")
    t3 = (OUT / "tables/table3_final_calibration_parameters.md").read_text(encoding="utf-8")
    t4 = (OUT / "tables/table4_threshold_mapping.md").read_text(encoding="utf-8")

    # ============================================================== technical report
    L = []
    A = L.append
    A("# C5: probability calibration analysis")
    A("")
    A("_Generated by `scripts/c5_write_docs.py` from the stored C5 artifacts. Validation data only: the locked test split was not opened, no model was trained and no inference was rerun._")
    A("")
    A("## 1. Objective")
    A("")
    A("A sigmoid output ranks cases; it is not automatically a probability. A displayed value of 70% is only meaningful if, among images scored near 70%, about 70% are positive. Class weighting during training (√-weighted BCE) deliberately inflates rare-class scores, so miscalibration is expected. C5 quantifies it and fits a per-class calibrator for the **displayed probability**. The **binary finding decision stays with the C4 policy** (raw score, F1-optimal threshold, No Finding rule); calibration does not replace it.")
    A("")
    A("## 2. Inputs and provenance")
    A("")
    A(f"- Model: DenseNet-121, √-weighted BCE (C2-B, provisional); checkpoint `{ck['path']}`, SHA-256 `{ck['sha256_recomputed']}`.")
    A(f"- Data: {n:,} validation images from {npat:,} patients, 14 observations in the fixed project order; uncertain labels excluded, blank labels scored negative.")
    A(f"- C4 reproduction: image/patient counts, class order, bit-identical scores, F1 thresholds, raw and final predictions and the No Finding rule all reproduce; macro metric difference {rep['max_abs_diff_macro_vs_c4_14']:.1e} ({rep['reproduced']}). The rule suppresses No Finding when any of the 12 pathology findings is positive; Support Devices does not.")
    A(f"- Logits: not stored. The stored scores are float32 sigmoid outputs ({lg['scores_are_float32_values']}), so logit(p) = log(p/(1−p)) is recovered with a worst-case rounding error of {lg['max_logit_rounding_error_from_float32_storage']:.1e} (median {lg['median_logit_rounding_error']:.1e}); no score reached the clipping bounds ({lg['n_clipped']} clipped; score range {lg['min_score']:.1e}–{lg['max_score']:.4f}). No inference was rerun.")
    A("")
    A("## 3. Calibration methods")
    A("")
    A("All calibrators are fitted per class on logits of the valid (non-uncertain) entries.")
    A("")
    A("- **Raw:** the sigmoid score unchanged (baseline).")
    A("- **Temperature scaling:** p = σ(z/T), T > 0, fitted on log T by bounded minimisation of log loss. One parameter; it can sharpen or soften but cannot correct a prevalence offset.")
    A("- **Platt scaling:** p = σ(a·z + b), fitted by Newton's method on the log loss; a slope ≤ 0 is flagged as pathological.")
    A("- **Isotonic regression (exploratory):** non-decreasing piecewise-linear map, outputs clipped to [1e-6, 1 − 1e-6] so log loss stays finite. It has many degrees of freedom and plateaus.")
    A("")
    A("Metrics: Brier score, log loss (primary), expected calibration error with 10 equal-frequency bins (supplementary: it depends on the binning), mean prediction vs prevalence, calibration slope (logistic regression of the outcome on logit(p)) and calibration-in-the-large (offset at slope 1). Ranking metrics (AUROC, AUPRC) are not used to choose a method.")
    A("")
    A("## 4. Patient-level cross-validation")
    A("")
    A(f"{cv['n_folds']}-fold cross-validation (seed {cv['seed']}) assigns whole patients to folds using multi-label iterative stratification over patients (valid positive images per class). No patient appears in two folds (checked: {cv['patient_overlap_between_folds']} overlaps). Images per fold: {', '.join(f'{x:,}' for x in cv['images_per_fold'])}; the smallest per-fold positive count is {min(cv['min_positives_per_class_per_fold'].values())} ({min(cv['min_positives_per_class_per_fold'], key=cv['min_positives_per_class_per_fold'].get)}). For every method, the calibrator is fitted on four folds and applied to the held-out fold; all metrics below come from the pooled out-of-fold predictions.")
    A("")
    A("## 5. Overall results (out-of-fold)")
    A("")
    A("**Table 1. Macro calibration metrics over the 14 observations.**")
    A("")
    A(t1)
    A(f"Platt scaling reduced the macro Brier score by {-pct(M('raw', 'brier'), M('platt', 'brier')):.1f}%, the macro log loss by {-pct(M('raw', 'log_loss'), M('platt', 'log_loss')):.1f}% and the macro ECE by {-pct(M('raw', 'ece'), M('platt', 'ece')):.0f}% relative to the raw scores. Temperature scaling improved all three only modestly (Brier {-pct(M('raw', 'brier'), M('temperature', 'brier')):.1f}%). Isotonic regression matched Platt on Brier and log loss (Brier {M('isotonic', 'brier'):.4f} vs {M('platt', 'brier'):.4f}; log loss {M('isotonic', 'log_loss'):.4f} vs {M('platt', 'log_loss'):.4f}) and had a lower ECE ({M('isotonic', 'ece'):.4f} vs {M('platt', 'ece'):.4f}).")
    A("")
    A("## 6. Per-class results")
    A("")
    A("**Table 2. Raw versus selected calibration (out-of-fold).**")
    A("")
    A(t2)
    A(f"- **Largest improvements (Brier):** " + ", ".join(f"{i} ({r.d_brier:.1f}%)" for i, r in top.iterrows()) + ". These are low-prevalence classes whose raw scores are inflated: mean raw score vs prevalence is " + "; ".join(f"{i} {sel.loc[i, 'raw_mean_score']:.3f} vs {sel.loc[i, 'prevalence']:.3f}" for i in ("Pneumonia", "Pleural Other", "Lung Lesion", "No Finding")) + ".")
    A(f"- **Little or no improvement:** " + ", ".join(f"{i} ({r.d_brier:.1f}%)" for i, r in low.iterrows()) + ". These are the four most prevalent classes, whose raw scores already matched prevalence closely. **No class got worse** on Brier or log loss.")
    A(f"- **Slopes:** raw calibration slopes range {sel.raw_cal_slope.min():.2f}–{sel.raw_cal_slope.max():.2f} (all below 1, i.e. over-confident); calibrated out-of-fold slopes are {sel.calibrated_cal_slope.min():.3f}–{sel.calibrated_cal_slope.max():.3f}. Calibrated mean predictions are within {mean_gap_cal.max():.4f} of prevalence for every class.")
    A("")
    A("## 7. Selected final calibrators")
    A("")
    A(f"Selection rule (declared before any result): among calibrators with no pathological fit and no C4-decision mismatch, take the simplest one within {res['selection_rule']['tolerance_rel']:.1%} of the best on **both** Brier and log loss; if one method is chosen for at least {res['selection_rule']['uniform_min_classes']} classes and using it everywhere costs at most {res['selection_rule']['uniform_max_rel_loss']:.0%} in every class, use it uniformly.")
    A("")
    A(f"- Per-class choices: {per_class_counts}. Platt was chosen for {uni['n_classes_selected']} classes; raw (Lung Opacity) and temperature (Pleural Effusion) were chosen for the others only because they came within the tolerance of Platt there.")
    A(f"- Applying Platt uniformly costs at most {100 * uni['worst_relative_loss_if_uniform']:.2f}% in any class, so **Platt scaling is used for all 14 classes** (`final_calibrators.json`).")
    A(f"- Isotonic was eligible but not chosen: it is not better than Platt on the primary metrics, it only provides a non-decreasing map (plateaus), and it has far more parameters. Its lower ECE is supplementary evidence.")
    A(f"- Guardrails: " + ("no calibrator was flagged (no non-positive or extreme Platt slope, no temperature at the search boundary, no isotonic fit with fewer than 5 output levels)." if not flagged else f"flags raised: {flagged}.") + f" Platt slopes across folds vary by at most {fold_spread:.3f} within a class.")
    A("")
    A("**Table 3. Final Platt parameters** (fitted on the full validation set after method selection).")
    A("")
    A(t3)
    A(f"Slopes range {a_rng[0]:.3f}–{a_rng[1]:.3f} and intercepts {b_rng[0]:.3f} to {b_rng[1]:.3f}; the rare classes have the smallest slopes and the most negative intercepts.")
    A("")
    A("## 8. Relationship to the C4 thresholds")
    A("")
    A("Calibration does not replace the C4 operating policy. Because Platt scaling with a positive slope is strictly increasing, each raw F1-optimal threshold maps to a calibrated-equivalent threshold that gives the same decision for every image.")
    A("")
    A("**Table 4. Threshold mapping.**")
    A("")
    A(t4)
    A(f"Decision mismatches across all {n:,} images: **{res['total_threshold_decision_mismatches']}** in every class. Applying the C4 No Finding rule to the calibrated-side decisions reproduces the C4 final predictions exactly. Calibrated-equivalent thresholds range {cal_thr_rng[0]:.3f}–{cal_thr_rng[1]:.3f}. Calibrated probabilities should be displayed alongside, not instead of, the C4 binary calls: a finding with a calibrated probability of 30% may still be called positive.")
    A("")
    A("## 9. Reliability analysis")
    A("")
    A("Figure 3 shows equal-frequency reliability curves (10 bins) for the rarest (Pleural Other), median-prevalence (Pneumothorax) and most prevalent (Support Devices) classes. Per class, " + rel_txt + ". The raw pattern therefore differs by class: Pneumothorax is clearly over-predicted, Pleural Other is over-predicted mainly in the highest-scoring bins, and Support Devices is under-predicted in most bins. Calibrated curves stay close to the diagonal in all three. Figure 5 shows the pattern across all classes: the raw mean score exceeds prevalence in " + f"{n_over} of 14 classes (not in {not_over}), while the calibrated means coincide with prevalence. The ranking is preserved: final calibrated AUROC differs from raw by at most " + f"{fin_auroc_dev:.1e} and AUPRC by at most {fin_auprc_dev:.1e} (identical up to floating-point ties); pooled out-of-fold AUROC differs by at most {oof_auroc_dev:.4f} because each fold uses a slightly different monotone map.")
    A("")
    A("## 10. Limitations")
    A("")
    A("- Calibration was developed and evaluated on validation data (out-of-fold, so each evaluated image was not used to fit its own calibrator). The final calibrators were then fitted on all validation data and have no further independent evaluation.")
    A("- The locked test split has not been evaluated; calibration on it is the next independent check.")
    A("- Rare classes have limited positives (smallest per-fold count " + f"{min(cv['min_positives_per_class_per_fold'].values())}); their calibration curves rest on few events per bin.")
    A("- Calibration can drift under dataset shift (different hospitals, scanners, label sources).")
    A("- A calibrated probability here means P(label positive | image) under the project's label definition (uncertain excluded, blank scored negative, report-derived labels). It is not the probability that the finding is truly present.")
    A("- Calibration is per class; it does not guarantee joint calibration across the 14 outputs.")
    A("- The loss was chosen provisionally; a different final model requires refitting the calibrators.")
    A("- The effect on report generation has not been tested.")
    A("")
    A("## 11. Decision")
    A("")
    A(f"Carry **Platt-calibrated probabilities** (`final_calibrators.json`, one calibrator per class, fitted on the full validation set) to the final pipeline as the displayed probabilities. Keep the C4 policy for binary calls; use the calibrated-equivalent thresholds only to show where each call falls on the probability scale. Raw sigmoid scores remain model scores and must not be shown as probabilities.")
    A("")
    (OUT / "CALIBRATION_ANALYSIS.md").write_text("\n".join(L), encoding="utf-8")

    # ============================================================== manuscript Methods
    methods = f"""# Methods: probability calibration (C5)

## Rationale and calibration methods

The sigmoid outputs of a classifier trained with a class-weighted loss are model scores, not necessarily probabilities. To obtain interpretable probabilities, we calibrated the output of each of the 14 CheXpert observations separately, using the logit of the stored sigmoid score (recovered as log(p/(1−p)); the scores were stored in single precision, giving a worst-case logit error of {lg['max_logit_rounding_error_from_float32_storage']:.0e}). Four options were compared: the raw score; temperature scaling, p = σ(z/T) with T > 0; Platt scaling, p = σ(az + b), with a flag for non-positive or extreme slopes; and isotonic regression, a non-decreasing map used as an exploratory comparator because it can overfit in rare classes. Calibrators were fitted by minimising log loss on valid labels only (uncertain labels excluded, blank labels treated as negative).

## Patient-level cross-validation

Calibration quality was estimated from out-of-fold predictions. The {n:,} validation images ({npat:,} patients) were split into {cv['n_folds']} folds with a fixed seed; all images of a patient were assigned to a single fold, using multi-label iterative stratification over patients to balance positives per class. For each method, calibrators were fitted on four folds and applied to the fifth, and the held-out predictions were pooled. No patient contributed to both fitting and evaluation within a fold.

## Metrics and method selection

We report the Brier score and log loss (primary), the expected calibration error with ten equal-frequency bins (supplementary), the mean prediction against prevalence, and the calibration slope and intercept. Methods were not chosen using AUROC or AUPRC. A selection rule was fixed before the results were examined: among calibrators without pathological fits (non-positive or extreme Platt slope, temperature at the search boundary, isotonic fits with very few output levels) and able to reproduce the binary decisions of the operating policy, the simplest method within {res['selection_rule']['tolerance_rel']:.1%} of the best on both Brier score and log loss was chosen for each class. If one method was chosen for at least {res['selection_rule']['uniform_min_classes']} classes and applying it to all classes cost at most {res['selection_rule']['uniform_max_rel_loss']:.0%} in every class, it was adopted uniformly.

## Final calibrators and relation to the operating policy

The selected calibrators were then refitted on the full validation set. The binary decision policy was left unchanged: findings were still called positive using the raw score and the class-specific F1-optimal thresholds, with the No Finding rule suppressing No Finding when any of the twelve pathology observations was positive. Each raw threshold was mapped through its calibrator to a calibrated-equivalent threshold, and we verified for every image and class that the raw and calibrated decisions were identical. As a sanity check, AUROC and AUPRC were compared before and after calibration without using them for selection.

## Data handling

All calibration analyses used the validation partition only, with the stored model scores; no model was retrained and no inference was repeated. The held-out test partition was not used at any point and remains unevaluated, so that it can provide an independent assessment once the complete classifier configuration, including the calibrators, has been frozen. Calibrated outputs are described as probabilities only where they refer to the calibrated values; raw sigmoid outputs are referred to as scores.
"""
    mw = wc(methods)
    (OUT / "MANUSCRIPT_C5_METHODS.md").write_text(methods, encoding="utf-8")

    # ============================================================== manuscript Results
    results = f"""# Results: probability calibration (C5)

## Baseline calibration quality

On the validation set ({n:,} images, {npat:,} patients), the raw sigmoid scores were systematically over-confident, most strongly for low-prevalence observations. Across the 14 observations the macro Brier score was {M('raw', 'brier'):.4f}, the macro log loss {M('raw', 'log_loss'):.4f} and the macro expected calibration error {M('raw', 'ece'):.4f}. The mean raw score exceeded the observed prevalence in {n_over} of 14 classes (not in {not_over}): for example {sel.loc['Pneumonia', 'raw_mean_score']:.3f} versus {sel.loc['Pneumonia', 'prevalence']:.3f} for Pneumonia, {sel.loc['Pleural Other', 'raw_mean_score']:.3f} versus {sel.loc['Pleural Other', 'prevalence']:.3f} for Pleural Other, and {sel.loc['No Finding', 'raw_mean_score']:.3f} versus {sel.loc['No Finding', 'prevalence']:.3f} for No Finding (Figure 5). Raw calibration slopes ranged from {sel.raw_cal_slope.min():.2f} to {sel.raw_cal_slope.max():.2f}.

## Comparison of calibration methods

Using patient-level five-fold out-of-fold predictions (Table 1), temperature scaling gave a small improvement (macro Brier score {M('temperature', 'brier'):.4f}, log loss {M('temperature', 'log_loss'):.4f}, ECE {M('temperature', 'ece'):.4f}), consistent with it being unable to correct a prevalence offset. Platt scaling gave substantially lower values (Brier {M('platt', 'brier'):.4f}, log loss {M('platt', 'log_loss'):.4f}, ECE {M('platt', 'ece'):.4f}), corresponding to reductions of {-pct(M('raw', 'brier'), M('platt', 'brier')):.1f}%, {-pct(M('raw', 'log_loss'), M('platt', 'log_loss')):.1f}% and {-pct(M('raw', 'ece'), M('platt', 'ece')):.0f}% relative to the raw scores. Isotonic regression performed similarly to Platt scaling on the Brier score ({M('isotonic', 'brier'):.4f}) and log loss ({M('isotonic', 'log_loss'):.4f}) with a lower ECE ({M('isotonic', 'ece'):.4f}), but offered no advantage on the primary metrics. No calibrator showed a pathological fit in any fold.

## Per-class findings

Improvements were concentrated in the low-prevalence classes (Table 2, Figures 1, 2 and 4). The largest Brier score reductions were for {', '.join(f"{i} ({-r.d_brier:.1f}%)" for i, r in top.iterrows())}. The smallest changes were for the most prevalent observations, {', '.join(f"{i} ({-r.d_brier:.1f}%)" for i, r in low.iterrows())}, whose raw scores already matched prevalence closely. Calibration did not worsen the Brier score or log loss of any class. After calibration, out-of-fold calibration slopes were {sel.calibrated_cal_slope.min():.3f} to {sel.calibrated_cal_slope.max():.3f}, and the mean predicted probability was within {mean_gap_cal.max():.4f} of the observed prevalence for every class.

## Selected calibrator and reliability

Under the pre-specified rule, Platt scaling was selected for {uni['n_classes_selected']} classes individually; the two remaining classes were within the tolerance of Platt scaling, and applying it uniformly cost at most {100 * uni['worst_relative_loss_if_uniform']:.2f}% in any class. Platt scaling was therefore used for all 14 observations (Table 3), with slopes between {a_rng[0]:.3f} and {a_rng[1]:.3f} and intercepts between {b_rng[0]:.3f} and {b_rng[1]:.3f}. Reliability curves based on equal-frequency bins showed class-specific raw behaviour (Figure 3): for Pneumothorax the observed fraction was below the mean prediction in {rel[('Pneumothorax','raw')][0]} of {rel[('Pneumothorax','raw')][1]} bins (largest gap {rel[('Pneumothorax','raw')][2]:.3f}), for Pleural Other the raw scores were over-predicted mainly in the highest bins (largest gap {rel[('Pleural Other','raw')][2]:.3f}), and for Support Devices they were under-predicted in most bins ({rel[('Support Devices','raw')][1]-rel[('Support Devices','raw')][0]} of {rel[('Support Devices','raw')][1]}). The out-of-fold calibrated values followed the diagonal closely, with largest gaps of {rel[('Pleural Other','calibrated_oof')][2]:.3f}, {rel[('Pneumothorax','calibrated_oof')][2]:.3f} and {rel[('Support Devices','calibrated_oof')][2]:.3f}.

## Threshold equivalence and ranking

The binary decisions of the operating policy were unchanged. Each class-specific F1-optimal threshold was mapped through its calibrator (Table 4), and the calibrated decisions matched the raw decisions for all {n:,} images in all 14 classes ({res['total_threshold_decision_mismatches']} mismatches); applying the No Finding rule to the calibrated-side decisions reproduced the final predictions exactly. Because the Platt maps are strictly increasing, AUROC and AUPRC were unchanged (maximum absolute differences {fin_auroc_dev:.1e} and {fin_auprc_dev:.1e}). ## Stability and interpretation

Fits were stable across folds: the Platt slope of any class varied by at most {fold_spread:.3f} between folds, and the smallest number of positive labels in any class and fold was {min(cv['min_positives_per_class_per_fold'].values())}, so rare-class estimates rest on few events and should be read with that in mind. Pooled out-of-fold AUROC differed from the raw AUROC by at most {oof_auroc_dev:.4f}, reflecting small differences between the fold-specific monotone maps rather than any change in ranking. Calibration therefore changed what the numbers mean, not which images are called positive. Raw outputs remain model scores; only the calibrated values should be presented as probabilities.

## Scope of the evidence

These results are validation-set estimates; the final calibrators were fitted on the same validation data, the held-out test set has not been evaluated, and the probabilities refer to the project's report-derived label definition, with uncertain labels excluded and blank labels treated as negative. Calibration may not transfer to other institutions or labelling methods.
"""
    rw = wc(results)
    (OUT / "MANUSCRIPT_C5_RESULTS.md").write_text(results, encoding="utf-8")
    assert 400 <= mw <= 600 and 600 <= rw <= 900, (mw, rw)

    # ============================================================== captions
    fc = f"""# Figure captions (C5)

All figures: CheXpert validation partition ({n:,} frontal images, {npat:,} patients); calibrated values are out-of-fold from patient-level {cv['n_folds']}-fold cross-validation; raw values are the sigmoid scores of a DenseNet-121 trained with √-weighted binary cross-entropy. Uncertain labels are excluded and blank labels are scored negative. Where markers coincide, the raw marker is hidden behind the calibrated one.

**Figure 1. Brier score before and after calibration.** Per-class Brier score of the raw sigmoid score and of Platt-calibrated probabilities (out-of-fold). The x-axis is logarithmic. Calibration lowered the Brier score in all 14 classes, most for low-prevalence classes (e.g. {top.index[0]}, {-top.iloc[0].d_brier:.0f}%).

**Figure 2. Log loss before and after calibration.** As Figure 1 for the log loss (logarithmic x-axis). Log loss decreased in all 14 classes.

**Figure 3. Reliability curves for three representative classes.** Observed positive fraction against mean predicted value in 10 equal-frequency bins, for the rarest (Pleural Other), median-prevalence (Pneumothorax) and most prevalent (Support Devices) classes, using the raw score and the out-of-fold Platt-calibrated probability. The diagonal is ideal calibration. Raw scores are over-predicted for Pneumothorax and in the highest bins for Pleural Other, and under-predicted in most bins for Support Devices; the calibrated values follow the diagonal closely.

**Figure 4. Change in calibration metrics per class.** Percentage change in Brier score and log loss from the raw score to the out-of-fold calibrated probability (negative values denote improvement). Changes ranged from {sel.d_brier.min():.1f}% to {sel.d_brier.max():.1f}% for the Brier score.

**Figure 5. Mean predicted value against observed prevalence.** For each class, the observed prevalence, the mean raw sigmoid score and the mean out-of-fold calibrated probability (logarithmic x-axis). Raw means exceeded prevalence in {n_over} of 14 classes (not in {not_over}); calibrated means coincided with prevalence.
"""
    (OUT / "FIGURE_CAPTIONS.md").write_text(fc, encoding="utf-8")
    tc = """# Table captions (C5)

**Table 1. Comparison of calibration methods.** Macro Brier score, log loss and expected calibration error (10 equal-frequency bins) over the 14 observations for the raw score, temperature scaling, Platt scaling and isotonic regression, from patient-level five-fold out-of-fold predictions on the validation set.

**Table 2. Per-class calibration, raw versus selected calibrator.** Prevalence, Brier score, log loss and expected calibration error of the raw sigmoid score and of the selected calibrator (out-of-fold), with the selected method.

**Table 3. Final calibration parameters.** Platt-scaling slope and intercept of p = sigmoid(a * logit(score) + b) for each observation, with the number of validation images and positives used for fitting (full validation set, after method selection).

**Table 4. Mapping of the C4 thresholds to the calibrated scale.** Raw F1-optimal threshold, calibrated-equivalent threshold, and the number of validation images whose binary decision differs between raw and calibrated outputs.
"""
    (OUT / "TABLE_CAPTIONS.md").write_text(tc, encoding="utf-8")
    idx = """# C5 journal asset index

| Asset | File | Purpose | Suggested manuscript section |
|---|---|---|---|
| Figure 1 | `figures/fig1_brier_raw_vs_calibrated.{png,pdf,svg}` | Per-class Brier score, raw vs calibrated | Results |
| Figure 2 | `figures/fig2_logloss_raw_vs_calibrated.{png,pdf,svg}` | Per-class log loss, raw vs calibrated | Results / Supplementary |
| Figure 3 | `figures/fig3_reliability_curves.{png,pdf,svg}` | Reliability curves for rare, medium and common classes | Results |
| Figure 4 | `figures/fig4_calibration_change_per_class.{png,pdf,svg}` | Per-class relative change in calibration metrics | Results |
| Figure 5 | `figures/fig5_mean_probability_vs_prevalence.{png,pdf,svg}` | Over-/under-confidence pattern across all classes | Results / Discussion |
| Table 1 | `tables/table1_calibration_method_comparison.{csv,md,tex}` | Macro comparison of calibration methods | Results |
| Table 2 | `tables/table2_per_class_raw_vs_calibrated.{csv,md,tex}` | Per-class raw vs selected calibration | Results / Supplementary |
| Table 3 | `tables/table3_final_calibration_parameters.{csv,md,tex}` | Final Platt parameters | Supplementary |
| Table 4 | `tables/table4_threshold_mapping.{csv,md,tex}` | Raw to calibrated threshold mapping, decision mismatches | Results / Supplementary |
| Technical report | `CALIBRATION_ANALYSIS.md` | Full methods, results, limitations, decision | Supplementary / internal |
| Methods draft | `MANUSCRIPT_C5_METHODS.md` | Manuscript-ready Methods text | Methods |
| Results draft | `MANUSCRIPT_C5_RESULTS.md` | Manuscript-ready Results text | Results |
| Captions | `FIGURE_CAPTIONS.md`, `TABLE_CAPTIONS.md` | Journal captions | All |
| Calibrators | `final_calibrators.json` | Machine-readable final calibrators | Code release / Supplementary |
| Per-image output | `validation_predictions_calibrated.csv.gz` | Scores, calibrated probabilities, thresholds and decisions per image | Supplementary |
| Figure data | `figures/source_data/*.csv` | Exact values plotted in each figure | Supplementary |
"""
    (OUT / "C5_JOURNAL_ASSET_INDEX.md").write_text(idx, encoding="utf-8")
    print(json.dumps({"methods_words": mw, "results_words": rw}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
