"""F1 documents generated from the stored locked-test artifacts (no number typed by hand): FINAL_LOCKED_TEST_ANALYSIS.md, MANUSCRIPT_FINAL_TEST_METHODS.md,
MANUSCRIPT_FINAL_TEST_RESULTS.md, MANUSCRIPT_FINAL_DISCUSSION_POINTS.md, FINAL_FIGURE_CAPTIONS.md, FINAL_TABLE_CAPTIONS.md, FINAL_JOURNAL_ASSET_INDEX.md, UNIVERSITY_REPORT_FINAL_TEST.md.
Formatting of stored values only; nothing is computed or changed here.

    .venv\\Scripts\\python.exe -m scripts.f1_09_write_docs
"""

from __future__ import annotations

import json
import re

import pandas as pd

from src.f1.pipeline import F1

T, V = F1 / "test", F1 / "validation_dry_run"
js = lambda p: json.loads(p.read_text(encoding="utf-8"))  # noqa: E731
f3 = lambda v: f"{v:.3f}"  # noqa: E731
pc = lambda v: f"{100 * v:.1f}%"  # noqa: E731
wc = lambda t: len(t.split())  # noqa: E731


def main() -> int:
    t, v = js(T / "f1_summary.json"), js(V / "f1_summary.json")
    proto, marker, cf, ver = js(F1 / "F1_LOCKED_TEST_PROTOCOL.json"), js(T / "test_opened.json"), js(F1 / "f1_code_freeze.json"), js(F1 / "f1_freeze_verification.json")
    rec = (F1 / "F1_LOCKED_TEST_PROTOCOL.sha256").read_text(encoding="utf-8").split()
    pj_hash = rec[0]
    TS, VS = t["report"], v["report"]
    cmp_ = pd.read_csv(F1 / "validation_to_test_comparison.csv")
    rt = pd.read_csv(T / "retrieval_metrics_by_k.csv")
    R = lambda m, k=5: rt[(rt.metric == m) & (rt.K == k)].iloc[0]  # noqa: E731
    fl, ab, th, pr, cop, prov = t["population_flow"], TS["abstention"], TS["three_state"], TS["routing_prose_consistency"], TS["copying"], pd.read_csv(T / "provenance.csv").set_index("provenance")
    M = TS["metrics"]
    rtm, gl = t["runtime"], js(T / "generation_run_log.json")
    cl = t["classification"]
    cc, cp = cl["ci95"], cl["point"]
    fa = pd.read_csv(T / "failure_analysis.csv").set_index("category")
    pft = pd.read_csv(T / "report_per_finding_results.csv")
    pcl = pd.read_csv(T / "classification_per_class.csv")
    tabs = lambda n: (F1 / f"tables/{n}.md").read_text(encoding="utf-8")  # noqa: E731
    mci = lambda k: f"{f3(M[k]['value'])} (95% CI {f3(M[k]['ci95_low'])} to {f3(M[k]['ci95_high'])})"  # noqa: E731
    cci = lambda k: f"{f3(cc[k]['point'])} (95% CI {f3(cc[k]['ci95_low'])} to {f3(cc[k]['ci95_high'])})"  # noqa: E731
    dd = th["decided"]
    dci = lambda k: f"{f3(dd[k]['value'])} (95% CI {f3(dd[k]['ci95_low'])} to {f3(dd[k]['ci95_high'])})"  # noqa: E731
    P3, P4 = TS["n_primary_P3_with_final_report"], TS["n_clinical_P4"]
    sc3 = th["state_counts_P3"]
    rn, ra = (next(r for r in th["reference_stratified"] if r["reference_state"] == k) for k in ("normal", "abnormal"))

    def where(metric_row) -> str:
        lo, hi, x = metric_row.validation_ci95_low, metric_row.validation_ci95_high, metric_row.test
        if pd.isna(lo):
            return "no interval available"
        return "inside the validation 95% interval" if lo <= x <= hi else "outside the validation 95% interval"

    cmp_rows = {r.metric: r for r in cmp_.itertuples()}
    out_of_val = [m for m, r in cmp_rows.items() if not pd.isna(r.validation_ci95_low) and not (r.validation_ci95_low <= r.test <= r.validation_ci95_high)]
    cmp_txt = "; ".join(f"{m} {f3(r.validation) if r.group != 'system' or 'rate' not in m else f3(r.validation)} to {f3(r.test)} ({r.test_minus_validation:+.3f})" for m, r in cmp_rows.items() if m not in ("abnormal-routing -> normal-prose rate (%)",))
    prose_v, prose_t = VS["routing_prose_consistency"]["abnormal_routing_to_normal_prose_rate_P3"], pr["abnormal_routing_to_normal_prose_rate_P3"]
    gap5 = R("jaccard_truth")
    caveat = ("IU X-Ray labels are MeSH-derived and incomplete, the classifier is applied out of domain (CheXpert to IU), one small quantised model was run once with greedy decoding, the bootstrap resamples studies (no patient identifier), "
              "and nothing here shows clinical benefit; the system is a research prototype.")
    gen_note = "Regenerating three validation reports in the pre-test dry run gave identical text for two and a semantically equivalent rewording for one, so local GPU generation is not bitwise reproducible."

    # ================================================================ FINAL_LOCKED_TEST_ANALYSIS.md
    A_ = []
    A = A_.append
    A("# F1: one-shot locked end-to-end evaluation")
    A("")
    A(f"_Generated by `scripts/f1_09_write_docs.py` from the stored locked-test artifacts. The frozen end-to-end system (configuration hash `{proto['final_system_config_sha256']}`) was evaluated once on the locked retrieval/end-to-end test split of {fl['locked_or_validation_studies']} IU X-Ray studies. No component was changed after the test was opened._")
    A("")
    A(f"> **Summary.** {fl['locked_or_validation_studies']} locked studies; {fl['primary_end_to_end_set_P3_(classified_and_usable_reference_report)']} in the primary end-to-end set and {P4} in the clinical-finding subset. Macro AUROC {cci('macro_auroc')}; finding F1 {mci('f1')}, precision {mci('precision')}, recall {mci('recall')}; hallucination rate {mci('hallucination_rate')}; "
      f"classifier FP propagation {mci('clf_fp_propagation')}, TP retention {mci('tp_retention')}. The guard routed {sc3['normal']} studies normal, {sc3['abnormal']} abnormal and {sc3['indeterminate']} indeterminate ({pc(sc3['indeterminate'] / P3)}); among decided studies normal recall was {dci('normal_recall_among_decided')} and abnormal recall {dci('abnormal_recall_among_decided')}, decision coverage {dci('decision_coverage')}. "
      f"Among abnormal-routed studies {pr['abnormal_routed_P3']['prose_normal']} of {pr['abnormal_routed_P3']['n']} ({prose_t:.1f}%) have report prose read as normal (validation {prose_v:.1f}%). {caveat}")
    A("")
    A("## 1. Pre-registration, freeze and one-shot opening")
    A("")
    A(f"Freeze identifiers verified before any test access: configuration hash `{proto['final_system_config_sha256']}`, G1 prompt `{proto['g1_prompt_sha256']}`, guard `{proto['guard_module_sha256']}` (all checks passed: {ver['all_identifiers_verified']}). The protocol (`F1_LOCKED_TEST_PROTOCOL.json`, SHA-256 `{pj_hash}`) was registered {proto['created_utc']} UTC at commit `{proto['git_commit_head']}`, "
      f"before any locked-test report content was read; the locked-test study-ID list hash is `{proto['locked_test']['study_ids_sha256']}`. All analysis code was developed on the validation partition only and had to reproduce the stored validation results (classifier scores to 2e-16, all 547 validation prompts byte-identical, retrieval and report metrics identical) before the one-shot gate wrote the code-freeze record ({cf['frozen_utc']} UTC, combined hash `{cf['combined_sha256']}`) and opened the test ({marker['opened_utc']} UTC).")
    A("")
    A("## 2. Population")
    A("")
    A(tabs("table1_locked_test_population"))
    A(f"No study was excluded because of its content; the {fl['without_frontal_image']} studies without a frontal image cannot be processed by an image-based system and are reported as such, no image failed the validator, and {fl['classified_without_usable_reference_report']} classified study has no usable reference report.")
    A("")
    A("## 3. Final classification metrics (frozen classifier, IU test labels)")
    A("")
    A(tabs("table2_final_classifier_metrics"))
    A(f"Macro AUROC {cci('macro_auroc')}, macro AUPRC {cci('macro_auprc')}, macro F1 {cci('macro_f1')}, Brier {cci('macro_brier')}, macro ECE {cci('macro_ece')} (the bootstrap interval of the binned ECE lies slightly above the point estimate, a known bias of the estimator). "
      f"{cl['n_classes_defined']} of 14 classes have a defined AUROC; undefined: {', '.join(cl['undefined_classes'])} (no test positives). Labels are the MeSH-mapped IU findings, so precision values are lower bounds and the classifier is evaluated out of domain.")
    A("")
    A(tabs("table3_per_class_classifier_metrics"))
    A("## 4. Routing guard")
    A("")
    A(f"Primary set: normal {sc3['normal']} ({pc(sc3['normal'] / P3)}), abnormal {sc3['abnormal']} ({pc(sc3['abnormal'] / P3)}), indeterminate {sc3['indeterminate']} ({pc(sc3['indeterminate'] / P3)}); the state comes from the frozen routing rule and not from generated prose. Path C studies (no label positive, No Finding not positive) triggered no retrieval and no model call: {t['report']['n_primary_P3_with_final_report'] - gl['n_cached_success']} studies without a generation record.")
    A("")
    A("## 5. Final retrieval evaluation (frozen R2, classifier query)")
    A("")
    A(tabs("table4_final_retrieval_metrics"))
    A(f"At the primary K = 5 (n = {int(R('jaccard_truth').n_queries)} queries) Jaccard was {f3(R('jaccard_truth').classifier_query)} (95% CI {f3(R('jaccard_truth').classifier_ci95_low)} to {f3(R('jaccard_truth').classifier_ci95_high)}), nDCG {f3(R('ndcg').classifier_query)}, finding coverage {f3(R('union_coverage').classifier_query)}, Hit {f3(R('hit').classifier_query)} and duplicate-text rate {f3(R('duplicate_text_rate').classifier_query)}. "
      f"With the oracle query (diagnostic only) Jaccard@5 was {f3(R('jaccard_truth').oracle_query)}, a gap of {R('jaccard_truth').gap_classifier_minus_oracle:+.3f} (95% CI {R('jaccard_truth').gap_ci95_low:+.3f} to {R('jaccard_truth').gap_ci95_high:+.3f}): retrieval quality is bounded by the quality of the classifier-derived query. K was not changed.")
    A("")
    A("## 6. Final report-generation metrics")
    A("")
    A(tabs("table5_final_report_generation_metrics"))
    A(f"All {gl['n_cached_success']} generations (Paths A and B, each exactly once) succeeded ({gl['n_failed']} persistent failures), {pc(TS['format_ok_rate'])} format-compliant. The METEOR value is the exact-match variant, not standard METEOR.")
    A("")
    A("## 7. Three-state system evaluation")
    A("")
    A(tabs("table6_three_state_system_metrics"))
    A(f"Reference-normal studies were routed normal {rn['routed_normal_pct']:.1f}%, abnormal {rn['routed_abnormal_pct']:.1f}% and indeterminate {rn['routed_indeterminate_pct']:.1f}%; reference-abnormal studies normal {ra['routed_normal_pct']:.1f}%, abnormal {ra['routed_abnormal_pct']:.1f}% and indeterminate {ra['routed_indeterminate_pct']:.1f}%. Indeterminate studies are not forced into normal or abnormal.")
    A("")
    A("## 8. Abstention analysis (descriptive)")
    A("")
    A(f"{ab['n_abstained_P3']} studies ({ab['pct_abstained_P3']:.1f}% of P3) were abstained; {ab['n_abstained_P4']} have a reference ({ab['pct_abstained_P4']:.1f}% of P4): {ab['reference_normal_among_abstained']} reference-normal ({pc(ab['reference_normal_fraction'])}) and {ab['reference_abnormal_among_abstained']} reference-abnormal ({pc(ab['reference_abnormal_fraction'])}). "
      f"Findings in the abstained reference-abnormal studies: {', '.join(f'{k} {n}' for k, n in ab['findings_in_abstained_reference_abnormal'].items())}. Rare findings account for {ab['rare_instances_in_abstained']} of {ab['total_instances_in_abstained']} instances against {ab['rare_instances_in_all_reference_abnormal']} of {ab['total_instances_in_all_reference_abnormal']} overall; "
      f"{ab['abstained_reference_abnormal_with_a_rare_finding']} of {ab['reference_abnormal_among_abstained']} abstained and {ab['decided_reference_abnormal_with_a_rare_finding']} of {ab['decided_reference_abnormal_n']} decided reference-abnormal studies have a rare finding (Fisher exact p = {ab['fisher_exact_p_two_sided']:.2f}), so rare findings are not shown to be over-represented (very small counts). The guard was not altered.")
    A("")
    A("## 9. Routing / prose consistency")
    A("")
    A(f"Among {pr['abnormal_routed_P3']['n']} abnormal-routed studies the final prose was read as normal in {pr['abnormal_routed_P3']['prose_normal']} ({prose_t:.1f}%; 95% CI {100 * pr['abnormal_routing_to_normal_prose_rate_ci95'][0]:.1f}% to {100 * pr['abnormal_routing_to_normal_prose_rate_ci95'][1]:.1f}%), as abnormal in {pr['abnormal_routed_P3']['prose_abnormal']} and as indeterminate in {pr['abnormal_routed_P3']['prose_indeterminate']}. "
      f"On the validation set the same rate was {prose_v:.1f}%; it is a descriptive comparator and not a target. Normal-routed prose was normal in {pr['normal_routed_P3']['prose_normal']} of {pr['normal_routed_P3']['n']} studies and indeterminate-routed text is indeterminate in all {pr['indeterminate_routed_P3']['n']}. The reports were not repaired.")
    A("")
    A("## 10. Retrieval grounding and copying")
    A("")
    A(tabs("table11_supplementary_provenance"))
    A(f"Findings stated with retrieval-only provenance numbered {int(prov.loc['retrieval only', 'stated_findings'])}, of which {int(prov.loc['retrieval only', 'reference_supported'])} ({pc(prov.loc['retrieval only', 'share_supported'])}) are reference-supported; findings supported by both the classifier and the retrieved reports are reference-supported in {pc(prov.loc['classifier and retrieval', 'share_supported'])} of {int(prov.loc['classifier and retrieval', 'stated_findings'])}.")
    A("")
    A(tabs("table12_supplementary_copying"))
    A("")
    A("## 11. Rare findings")
    A("")
    A(tabs("table7_rare_finding_analysis"))
    A(f"Pooled retention of classifier true positives over the six rare findings was {TS['rare_pooled']['retained']} of {TS['rare_pooled']['classifier_true_positives']} ({pc(TS['rare_pooled']['tp_retention'])}). The test supports are very small (Enlarged Cardiomediastinum has none), so no strong claim is made.")
    A("")
    A("## 12. Validation to test (descriptive)")
    A("")
    A(tabs("table8_validation_to_test_comparison"))
    A(f"Differences are test minus validation and are not used for tuning. Test estimates outside the validation 95% interval: {', '.join(out_of_val) or 'none'}. Validation here means the IU validation partition processed by the same code (a dry run); the CheXpert C6 results are a different dataset and are not part of this comparison.")
    A("")
    A("## 13. Failure analysis (frozen taxonomy)")
    A("")
    A(tabs("table9_failure_analysis"))
    A(f"Categories are multi-label over the {P4} clinical-subset studies; {TS['no_failure_categories_1_to_8']} studies ({pc(TS['no_failure_categories_1_to_8'] / P4)}) fall in none of categories 1 to 8. Classifier error is the most frequent category ({int(fa.loc['1_classifier_error', 'n_studies'])} studies), followed by report-generator omission ({int(fa.loc['5_report_generator_omission', 'n_studies'])}); "
      f"abnormal routing with normal prose affects {int(fa.loc['7_abnormal_routing_normal_prose', 'n_studies'])} studies and retrieval-only unsupported findings {int(fa.loc['4_retrieval_only_unsupported_finding', 'n_studies'])}. No category was added after inspecting individual failures.")
    A("")
    A("## 14. Runtime and compute")
    A("")
    A(tabs("table10_runtime_compute"))
    A("## 15. Reproducibility notes")
    A("")
    A(f"{gen_note} The validation dry run reproduced every stored result; for the locked run the prompt and request hashes of all {gl['n_cached_success']} generations equal their rebuild (see `f1_final_integrity_report.json`).")
    A("")
    A("## 16. Limitations")
    A("")
    A(f"- {caveat}")
    A("- The classification population is the subset with a usable mapped truth; the 28 studies without a frontal image and the studies without a reference are not evaluable end to end.")
    A("- Rare-finding and per-class results rest on very small counts; some classes have one to five test positives and one has none.")
    A("- The abnormal-routing normal-prose inconsistency of the frozen G1 prompt remains and is reported, not repaired.")
    A("- Validation numbers for the comparison were computed with the same code on the IU validation partition, which was also used during development of earlier stages; test minus validation is therefore a generalisation check and not an independent re-selection.")
    A("")
    A("## 17. Conclusion")
    A("")
    A(f"The frozen end-to-end system was evaluated once on the locked test set without post-test changes. Its test estimates are close to validation for retrieval (Jaccard@5 {f3(R('jaccard_truth').classifier_query)} versus {f3(cmp_rows['Jaccard@5'].validation)}), somewhat lower for finding recall and F1, and the decision coverage fell from {f3(cmp_rows['decision coverage'].validation)} to {f3(cmp_rows['decision coverage'].test)} because more studies were indeterminate. Final model development is closed.")
    A("")
    (F1 / "FINAL_LOCKED_TEST_ANALYSIS.md").write_text("\n".join(A_), encoding="utf-8")

    # ================================================================ manuscript methods
    meth = f"""# Methods: one-shot locked end-to-end evaluation

## Frozen system and pre-registration

The final system comprised a frozen DenseNet-121 classifier (square-root-weighted binary cross-entropy, F1-optimal operating thresholds with a No Finding consistency rule, Platt calibration), a deterministic routing guard, frozen hybrid retrieval and a frozen single-agent retrieval-augmented generator. The retrieval query consisted of the three highest-probability classifier-positive findings; MiniLM dense retrieval and BM25 were fused by reciprocal-rank fusion (k = 60, depth 100) and the Top-5 reports (K = 5; no diversity reranking, phrase expansion or probability weighting) were given to the local model medgemma1.5:4b (greedy decoding, fixed seed, digest verified) with the frozen prompt. The guard routed each study from the classifier output alone: normal (No Finding positive and no pathology label positive), abnormal (any other study with a positive label) or indeterminate (no label positive; no retrieval, no model call, fixed message). The configuration (SHA-256 {proto['final_system_config_sha256'][:16]}...), prompt and guard hashes were verified before the test was touched. A protocol listing the populations, metrics, figures, tables, bootstrap, failure handling and failure taxonomy was hashed before any locked-test content was read, and all analysis code was frozen after it had reproduced the stored validation results.

## Test data and populations

The locked IU X-Ray test split contained {fl['locked_or_validation_studies']} studies. Each study's first frontal image was classified. Populations followed the validation rules: studies with a frontal image ({fl['with_frontal_image']}), classified studies, studies with a usable reference report (primary end-to-end set, {fl['primary_end_to_end_set_P3_(classified_and_usable_reference_report)']}) and studies with a usable MeSH-mapped reference ({P4} in the clinical-finding subset); no study was excluded for its content.

## Outcomes

Classification used the C6 definitions (AUROC, AUPRC, precision, recall, specificity, F1, balanced accuracy, Brier score, log loss and adaptive-bin ECE) against the mapped labels. Retrieval was evaluated at K = 1, 3, 5 and 10 by finding agreement (Jaccard, nDCG, finding coverage, exact-match Hit, duplicate-text rate), with an oracle-query diagnostic. Report quality used finding precision, recall and F1, macro F1, hallucination and omission rates, propagation of classifier false positives, retention of classifier true positives, ROUGE-L, BLEU-4 and an exact-match METEOR variant. The three-state analysis reported the routing distribution, routing by reference state, normal and abnormal recall among decided studies and decision coverage, and the abstention composition. We also measured the share of abnormal-routed studies whose prose reads as normal, the provenance of stated findings, copying of retrieved text, rare-finding behaviour, a frozen ten-category failure taxonomy and runtime. Intervals were 95% percentile intervals from 1,000 study-level bootstrap resamples (seed 42). Validation-to-test differences were computed with the same code on the validation partition.

## Safeguards

Each generation request was cached with its hash and the frozen options, failures would have been recorded and not replaced, and all prompts were verified against their rebuild. No parameter, prompt, threshold, routing rule or model selection was changed after the test was opened.
"""
    mw = wc(meth)
    (F1 / "MANUSCRIPT_FINAL_TEST_METHODS.md").write_text(meth, encoding="utf-8")

    resu = f"""# Results: one-shot locked end-to-end evaluation

## Population

Of {fl['locked_or_validation_studies']} locked studies, {fl['with_frontal_image']} had a frontal image, {fl['primary_end_to_end_set_P3_(classified_and_usable_reference_report)']} formed the primary end-to-end set and {P4} the clinical-finding subset ({fl['reference_normal_in_P4']} reference-normal) (Table 1). The guard routed {sc3['normal']} studies normal, {sc3['abnormal']} abnormal and {sc3['indeterminate']} indeterminate ({pc(sc3['indeterminate'] / P3)}).

## Classification

The frozen classifier reached a macro AUROC of {cci('macro_auroc')} and macro AUPRC of {cci('macro_auprc')} over {cl['n_classes_defined']} defined classes (micro AUROC {f3(cp['micro_auroc'])}, micro AUPRC {f3(cp['micro_auprc'])}); macro precision {f3(cp['macro_precision'])}, recall {f3(cp['macro_recall'])}, specificity {f3(cp['macro_specificity'])}, F1 {f3(cp['macro_f1'])}, balanced accuracy {f3(cp['macro_balanced_accuracy'])}; Brier score {f3(cp['macro_brier'])}, log loss {f3(cp['macro_log_loss'])} and ECE {f3(cp['macro_ece'])} (Tables 2 and 3, Figures 1 and 2). Per-class AUROC ranged from {f3(pcl.auroc.min())} to {f3(pcl.auroc.max())}; Enlarged Cardiomediastinum had no test positives.

## Retrieval

At K = 5 the classifier query gave Jaccard {f3(R('jaccard_truth').classifier_query)}, nDCG {f3(R('ndcg').classifier_query)}, finding coverage {f3(R('union_coverage').classifier_query)}, Hit {f3(R('hit').classifier_query)} and a duplicate-text rate of {f3(R('duplicate_text_rate').classifier_query)}; the oracle query reached a Jaccard of {f3(R('jaccard_truth').oracle_query)} and coverage of {f3(R('union_coverage').oracle_query)} (Table 4, Figure 3).

## Report generation

On the clinical subset finding precision was {mci('precision')}, recall {mci('recall')}, F1 {mci('f1')} and macro F1 {mci('macro_f1')}; hallucination rate {mci('hallucination_rate')} and omission rate {mci('omission_rate')}; classifier false-positive propagation {mci('clf_fp_propagation')} and true-positive retention {mci('tp_retention')}; ROUGE-L {mci('rouge_l')}, BLEU-4 {mci('bleu4')} and the METEOR variant {mci('meteor_exact')} (Table 5, Figures 5 and 6). All {gl['n_cached_success']} generations succeeded in {rtm['generation']['mean_seconds_per_report']:.1f} s on average.

## Three-state system behaviour

Reference-normal studies were routed normal in {rn['routed_normal_pct']:.1f}%, abnormal in {rn['routed_abnormal_pct']:.1f}% and indeterminate in {rn['routed_indeterminate_pct']:.1f}%; reference-abnormal studies in {ra['routed_normal_pct']:.1f}%, {ra['routed_abnormal_pct']:.1f}% and {ra['routed_indeterminate_pct']:.1f}%. Among decided studies normal recall was {dci('normal_recall_among_decided')} and abnormal recall {dci('abnormal_recall_among_decided')}, with decision coverage {dci('decision_coverage')} (Table 6, Figure 7). Of the {ab['n_abstained_P4']} abstained studies with a reference, {ab['reference_normal_among_abstained']} were reference-normal and {ab['reference_abnormal_among_abstained']} reference-abnormal; rare findings were not over-represented (Fisher p = {ab['fisher_exact_p_two_sided']:.2f}). In {pr['abnormal_routed_P3']['prose_normal']} of {pr['abnormal_routed_P3']['n']} abnormal-routed studies ({prose_t:.1f}%) the prose was read as normal (validation {prose_v:.1f}%).

## Grounding, copying and rare findings

Stated findings with retrieval-only provenance numbered {int(prov.loc['retrieval only', 'stated_findings'])} ({pc(prov.loc['retrieval only', 'share_supported'])} reference-supported), against {pc(prov.loc['classifier and retrieval', 'share_supported'])} of {int(prov.loc['classifier and retrieval', 'stated_findings'])} findings supported by both sources. {pc(cop['copied_sentence_rate_mean'])} of sentences were copied verbatim from the study's own Top-5 and {pc(cop['whole_report_copy_rate'])} of reports copied a retrieved report entirely. Pooled retention of rare-finding classifier true positives was {TS['rare_pooled']['retained']} of {TS['rare_pooled']['classifier_true_positives']} (Table 7); counts are too small for strong claims.

## Validation to test and failure analysis

Test minus validation (Table 8, Figure 4): macro AUROC {cmp_rows['macro AUROC'].test_minus_validation:+.3f}, macro AUPRC {cmp_rows['macro AUPRC'].test_minus_validation:+.3f}, Jaccard@5 {cmp_rows['Jaccard@5'].test_minus_validation:+.3f}, finding F1 {cmp_rows['finding F1'].test_minus_validation:+.3f}, hallucination rate {cmp_rows['hallucination rate'].test_minus_validation:+.3f}, decision coverage {cmp_rows['decision coverage'].test_minus_validation:+.3f}. Estimates outside the validation interval: {', '.join(out_of_val) or 'none'}. In the frozen failure taxonomy (Table 9, Figure 8), {TS['no_failure_categories_1_to_8']} of {P4} studies ({pc(TS['no_failure_categories_1_to_8'] / P4)}) fell in none of categories 1 to 8; the most frequent categories were classifier error ({int(fa.loc['1_classifier_error', 'n_studies'])}), report-generator omission ({int(fa.loc['5_report_generator_omission', 'n_studies'])}) and normal/abnormal classifier mismatch ({int(fa.loc['2_normal_abnormal_classifier_mismatch', 'n_studies'])}).
"""
    rw = wc(resu)
    (F1 / "MANUSCRIPT_FINAL_TEST_RESULTS.md").write_text(resu, encoding="utf-8")

    disc = f"""# Final test: discussion points (for later manuscript assembly)

- **Generalisation.** Classification, retrieval and report metrics on the locked test are close to the validation estimates (retrieval Jaccard@5 {f3(cmp_rows['Jaccard@5'].validation)} to {f3(cmp_rows['Jaccard@5'].test)}; macro AUROC {f3(cmp_rows['macro AUROC'].validation)} to {f3(cmp_rows['macro AUROC'].test)}), with a larger drop in macro AUPRC ({cmp_rows['macro AUPRC'].test_minus_validation:+.3f}) and lower finding recall ({cmp_rows['finding recall'].test_minus_validation:+.3f}); intervals are wide because the test has {P4} clinical-subset studies.
- **Out-of-domain classifier.** The classifier was trained on CheXpert and applied to IU X-Ray with MeSH-derived labels; per-class AUROC ranges from {f3(pcl.auroc.min())} to {f3(pcl.auroc.max())}, and some classes have one to five positives or none.
- **Retrieval is limited by the query.** At K = 5 the classifier-query Jaccard is {f3(R('jaccard_truth').classifier_query)} against {f3(R('jaccard_truth').oracle_query)} for the oracle query, and {pc(R('duplicate_text_rate').classifier_query)} of retrieved texts are duplicates of another retrieved text; better classifier findings, not a larger K, would be needed to close the gap.
- **Abstention is a coverage trade-off.** {pc(sc3['indeterminate'] / P3)} of studies were indeterminate; decision coverage was {pc(dd['decision_coverage']['value'])}; decided-case recalls were {f3(dd['normal_recall_among_decided']['value'])} (normal) and {f3(dd['abnormal_recall_among_decided']['value'])} (abnormal). {ab['reference_abnormal_among_abstained']} of the {ab['n_abstained_P4']} abstained studies with a reference were reference-abnormal.
- **Routing/prose inconsistency persists.** {prose_t:.1f}% of abnormal-routed studies have prose read as normal (validation {prose_v:.1f}%); an application must show the routing state next to the prose.
- **Grounding.** Findings stated only because of the retrieved reports are mostly unsupported ({pc(prov.loc['retrieval only', 'share_supported'])} supported); findings supported by both the classifier and retrieval are supported in {pc(prov.loc['classifier and retrieval', 'share_supported'])} of cases.
- **Copying.** {pc(cop['copied_sentence_rate_mean'])} of sentences and {pc(cop['whole_report_copy_rate'])} of reports are copied from the study's own Top-5; the earlier multi-agent variant did not reduce propagation of classifier findings and was not selected.
- **Rare findings.** Retention of rare-finding classifier true positives is {TS['rare_pooled']['retained']} of {TS['rare_pooled']['classifier_true_positives']}; Lung Lesion and Pleural Other true positives were not retained in any report.
- **Reference limitation.** {int(fa.loc['10_reference_label_limitation', 'n_studies'])} of {P4} clinical-subset studies have unmapped or uncertain MeSH terms; hallucination and omission rates are therefore partly reference artefacts.
- **Runtime.** End-to-end compute was {rtm['total_end_to_end_seconds'] / 60:.1f} minutes for {gl['n_cached_success']} generated reports (mean {rtm['generation']['mean_seconds_per_report']:.1f} s per report) on a consumer GPU.
- **Reproducibility.** {gen_note}
- **Scope.** {caveat}
"""
    (F1 / "MANUSCRIPT_FINAL_DISCUSSION_POINTS.md").write_text(disc, encoding="utf-8")

    fc = f"""# Final test figure captions

Locked end-to-end test (IU X-Ray, {fl['locked_or_validation_studies']} studies; clinical subset {P4}; primary set {P3}). Blue = locked test; orange = validation dry run of the same code. Error bars: 95% study-level bootstrap intervals.

**Figure 1. Per-class classifier AUROC and AUPRC.** Frozen classifier on the locked test with MeSH-mapped labels; the number of test positives is shown per class; Enlarged Cardiomediastinum is undefined (no positives).

**Figure 2. Calibration.** Left: pooled reliability diagram with equal-frequency bins for calibrated probabilities (test and validation). Right: per-class adaptive-bin expected calibration error on the test.

**Figure 3. Retrieval at K = 1, 3, 5 and 10.** Jaccard, nDCG, finding coverage and exact-match Hit for the classifier query and for the oracle query (diagnostic only). The dotted line marks the frozen K = 5.

**Figure 4. Validation versus test classification metrics.** Macro AUROC, AUPRC, F1, Brier score and ECE.

**Figure 5. Final report precision, recall and F1.** Finding agreement with the mapped IU reference on the clinical subset (validation versus test).

**Figure 6. Hallucination, omission, classifier false-positive propagation and true-positive retention.** Clinical subset, validation versus test.

**Figure 7. Three-state system results.** Left: routing of reference-normal and reference-abnormal studies to normal, abnormal and indeterminate. Right: normal and abnormal recall among decided studies and decision coverage.

**Figure 8. Failure-category summary.** Share of the clinical subset in each frozen category; studies can belong to several categories; grey bars are limitation flags.
"""
    (F1 / "FINAL_FIGURE_CAPTIONS.md").write_text(fc, encoding="utf-8")
    tc = """# Final test table captions

**Table 1. Locked-test population.** Population flow from the 578 locked studies to the primary set, the clinical-finding subset and the routing counts.

**Table 2. Final classifier metrics.** Macro and micro ranking and threshold metrics, Brier score, log loss and ECE with 95% study-level bootstrap intervals.

**Table 3. Per-class classifier metrics.** AUROC, AUPRC, precision, recall, specificity, F1 and support per observation.

**Table 4. Final retrieval metrics.** Jaccard, nDCG, finding coverage, Hit and duplicate-text rate at K = 1, 3, 5, 10 for the classifier query and the oracle query, and their gap.

**Table 5. Final report-generation metrics.** Finding-level and text-overlap metrics on the locked test.

**Table 6. Three-state system metrics.** State distribution, routing by reference state, decided-case recalls, decision coverage, abstention and routing/prose consistency.

**Table 7. Rare-finding analysis.** Test support, precision, recall, F1 and classifier true-positive retention for the six rare findings.

**Table 8. Validation-to-test comparison.** Descriptive test minus validation differences for classification, retrieval, report generation and system metrics.

**Table 9. Failure analysis.** Frozen failure taxonomy over the clinical subset.

**Table 10. Runtime and compute.** Classifier, retrieval and generation runtime, tokens, GPU memory and model metadata.

**Table 11 (supplementary). Provenance of stated findings.** Classifier only, retrieval only, both, neither, with reference support.

**Table 12 (supplementary). Copying.** Sentence copying, whole-report copying and repeated-sentence rate with the frozen definitions.
"""
    (F1 / "FINAL_TABLE_CAPTIONS.md").write_text(tc, encoding="utf-8")
    idx = f"""# Final test journal asset index

| Asset | Main content | Suggested manuscript section |
|---|---|---|
| Table 1 `tables/table1_locked_test_population.*` | {fl['locked_or_validation_studies']} locked studies, {P3} primary, {P4} clinical subset | Methods / Results |
| Table 2 `tables/table2_final_classifier_metrics.*` | Macro AUROC {f3(cc['macro_auroc']['point'])}, AUPRC {f3(cc['macro_auprc']['point'])} | Results |
| Table 3 `tables/table3_per_class_classifier_metrics.*` | Per-class metrics | Results / Supplementary |
| Table 4 `tables/table4_final_retrieval_metrics.*` | Jaccard@5 {f3(R('jaccard_truth').classifier_query)} vs oracle {f3(R('jaccard_truth').oracle_query)} | Results |
| Table 5 `tables/table5_final_report_generation_metrics.*` | F1 {f3(M['f1']['value'])}, hallucination {f3(M['hallucination_rate']['value'])} | Results |
| Table 6 `tables/table6_three_state_system_metrics.*` | {sc3['indeterminate']} indeterminate; coverage {pc(dd['decision_coverage']['value'])} | Results |
| Table 7 `tables/table7_rare_finding_analysis.*` | Rare findings | Results / Supplementary |
| Table 8 `tables/table8_validation_to_test_comparison.*` | Test minus validation | Results / Discussion |
| Table 9 `tables/table9_failure_analysis.*` | Frozen failure taxonomy | Results / Discussion |
| Table 10 `tables/table10_runtime_compute.*` | Runtime | Methods / Supplementary |
| Tables 11-12 `tables/table11_*`, `table12_*` | Provenance, copying | Supplementary |
| Figures 1-8 `figures/fig*.png|pdf|svg` | See `FINAL_FIGURE_CAPTIONS.md` | Results |
| `F1_LOCKED_TEST_PROTOCOL.json` / `.md` / `.sha256` | Pre-registered protocol | Methods / Supplementary |
| `f1_code_freeze.json`, `f1_freeze_verification.json`, `test/test_opened.json` | Code freeze, freeze verification, one-shot opening | Methods / Supplementary |
| `f1_final_integrity_report.json` | Integrity verification | Supplementary |
| `FINAL_LOCKED_TEST_ANALYSIS.md`, `MANUSCRIPT_FINAL_TEST_*.md`, `UNIVERSITY_REPORT_FINAL_TEST.md` | Analysis and text material | Methods, Results, Discussion |
| `test/*.csv`, `test/report_per_study_results.csv` | All per-study test outputs | Supplementary data |
"""
    (F1 / "FINAL_JOURNAL_ASSET_INDEX.md").write_text(idx, encoding="utf-8")

    U = f"""# University report material: final locked test (F1)

_Insert-ready material generated from the stored artifacts. The test was opened once, after the protocol and the code were frozen; no component changed afterwards._

## Experimental setup

The frozen system is a DenseNet-121 chest X-ray classifier with F1-optimised thresholds, a No Finding consistency rule and Platt calibration; a deterministic routing guard; hybrid dense and BM25 retrieval of the Top-5 IU reports from the top-3 classifier findings; and a local single-agent language model (medgemma1.5:4b, greedy decoding) that writes a preliminary Findings and Impression. Studies with no positive classifier label are reported as indeterminate without retrieval or generation. The configuration, prompt and guard hashes were verified, a protocol was hashed, and analysis code that reproduced the validation results was frozen before the {fl['locked_or_validation_studies']} locked IU X-Ray studies were opened. {fl['with_frontal_image']} had a frontal image, {fl['primary_end_to_end_set_P3_(classified_and_usable_reference_report)']} formed the primary set and {P4} the clinical-finding subset. Metrics follow the validation definitions; intervals are 1,000-resample study-level bootstrap intervals (seed 42).

## Final classification results

Macro AUROC was {cci('macro_auroc')}, macro AUPRC {cci('macro_auprc')} and macro F1 {cci('macro_f1')}; Brier score {f3(cp['macro_brier'])} and ECE {f3(cp['macro_ece'])}. Per-class AUROC ranged from {f3(pcl.auroc.min())} to {f3(pcl.auroc.max())}; cardiomegaly ({f3(float(pcl[pcl.observation == 'Cardiomegaly'].auroc.iloc[0]))}) and pleural effusion ({f3(float(pcl[pcl.observation == 'Pleural Effusion'].auroc.iloc[0]))}) were among the best and support devices ({f3(float(pcl[pcl.observation == 'Support Devices'].auroc.iloc[0]))}) among the weakest. The classifier is applied out of domain and labels are derived from MeSH terms, so these values are descriptive.

## Retrieval results

At K = 5 Jaccard was {f3(R('jaccard_truth').classifier_query)}, nDCG {f3(R('ndcg').classifier_query)}, finding coverage {f3(R('union_coverage').classifier_query)} and Hit {f3(R('hit').classifier_query)}; with the oracle query Jaccard was {f3(R('jaccard_truth').oracle_query)}, so the classifier-derived query limits retrieval. {pc(R('duplicate_text_rate').classifier_query)} of the retrieved texts duplicate another retrieved text.

## Report-generation results

Finding precision {f3(M['precision']['value'])}, recall {f3(M['recall']['value'])}, F1 {f3(M['f1']['value'])}; hallucination rate {f3(M['hallucination_rate']['value'])}, omission rate {f3(M['omission_rate']['value'])}; classifier false-positive propagation {f3(M['clf_fp_propagation']['value'])} and true-positive retention {f3(M['tp_retention']['value'])}. {pc(cop['copied_sentence_rate_mean'])} of sentences and {pc(cop['whole_report_copy_rate'])} of reports are copied from the retrieved reports.

## End-to-end system results

The guard routed {sc3['normal']} studies normal, {sc3['abnormal']} abnormal and {sc3['indeterminate']} indeterminate. Among decided studies, normal recall was {f3(dd['normal_recall_among_decided']['value'])} and abnormal recall {f3(dd['abnormal_recall_among_decided']['value'])}; decision coverage was {pc(dd['decision_coverage']['value'])}. {prose_t:.1f}% of abnormal-routed studies had prose read as normal (validation {prose_v:.1f}%). Compared with validation, retrieval and classification are similar, while recall, F1 and coverage are lower (Table 8).

## Failure analysis

{TS['no_failure_categories_1_to_8']} of {P4} clinical-subset studies ({pc(TS['no_failure_categories_1_to_8'] / P4)}) had none of the first eight failure categories. Classifier error ({int(fa.loc['1_classifier_error', 'n_studies'])} studies) and report-generator omission ({int(fa.loc['5_report_generator_omission', 'n_studies'])}) were the most frequent; abnormal routing with normal prose occurred in {int(fa.loc['7_abnormal_routing_normal_prose', 'n_studies'])} and indeterminate abstention in {int(fa.loc['8_indeterminate_abstention', 'n_studies'])}.

## Limitations

{caveat} {gen_note} Several classes and all rare findings have very few test cases, the reference is incomplete for {int(fa.loc['10_reference_label_limitation', 'n_studies'])} of {P4} clinical-subset studies, and the frozen prompt's tendency to write normal-sounding prose for some abnormal-routed studies was reported and not repaired.
"""
    (F1 / "UNIVERSITY_REPORT_FINAL_TEST.md").write_text(U, encoding="utf-8")

    bad = []
    for n in ("FINAL_LOCKED_TEST_ANALYSIS.md", "MANUSCRIPT_FINAL_TEST_METHODS.md", "MANUSCRIPT_FINAL_TEST_RESULTS.md", "MANUSCRIPT_FINAL_DISCUSSION_POINTS.md", "FINAL_FIGURE_CAPTIONS.md", "FINAL_TABLE_CAPTIONS.md", "FINAL_JOURNAL_ASSET_INDEX.md", "UNIVERSITY_REPORT_FINAL_TEST.md"):
        txt = (F1 / n).read_text(encoding="utf-8")
        for pat in (r"clinically (optimal|safe|ready)", r"\bproves?\b", r"superior to", r"\{[a-z_]+\[[^}]*\}", r"\bnan\b", r"\bNone\b", r"anthropic", r"claude"):
            if re.search(pat, txt, re.I if pat in ("anthropic", "claude") else 0):
                bad.append((n, pat))
    print(json.dumps({"methods_words": mw, "results_words": rw, "wording_flags": bad, "out_of_validation_interval": out_of_val}))
    return 0 if not bad else 1


if __name__ == "__main__":
    raise SystemExit(main())
