"""Generate the four C2 loss-study configs from ONE shared base, so that the arms
differ ONLY in `loss` (plus experiment_name / output_dir).

    .venv\\Scripts\\python.exe -m scripts.make_c2_configs

Base = the C1 config with two documented protocol changes that apply to ALL arms:
  * checkpoint selection, early stopping AND the LR scheduler monitor validation macro AUPRC
  * TF32 off for training and evaluation (canonical inference policy, applied by the trainer)
Loss parameters were fixed here BEFORE any C2 validation result existed.
"""

from __future__ import annotations

import copy

import yaml

from src.utils.config import PROJECT_ROOT

BASE = PROJECT_ROOT / "configs/classifier/densenet121.yaml"
OUT = PROJECT_ROOT / "configs/classifier/c2"

ARMS = {
    "c2a_bce": {"type": "bce"},
    "c2b_sqrt_weighted_bce": {"type": "weighted_bce", "pos_weight_source": "train_split", "pos_weight_tempering": "sqrt"},
    "c2c_focal_gamma2": {"type": "focal", "gamma": 2.0, "alpha": None},
    # Ridnik et al. (ICCV 2021) default multi-label configuration
    "c2d_asl": {"type": "asl", "gamma_pos": 0.0, "gamma_neg": 4.0, "clip": 0.05},
}


def base_config() -> dict:
    cfg = yaml.safe_load(BASE.read_text(encoding="utf-8"))
    cfg["training"]["monitor"] = "val_macro_auprc"
    cfg["scheduler"]["monitor"] = "val_macro_auprc"
    cfg["loss"] = None
    return cfg


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, loss in ARMS.items():
        cfg = copy.deepcopy(base_config())
        cfg["experiment_name"] = name
        cfg["output_dir"] = f"results/classification/experiments/{name}"
        cfg["loss"] = loss
        header = (f"# C2 loss study arm '{name}'. GENERATED by scripts/make_c2_configs.py - do not edit by hand.\n"
                  "# Identical to the other C2 arms except `loss`, `experiment_name` and `output_dir`.\n")
        (OUT / f"{name}.yaml").write_text(header + yaml.safe_dump(cfg, sort_keys=False), encoding="utf-8")
        print("wrote", OUT / f"{name}.yaml")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
