"""Write results/classification/experiments/LOSS_COMPARISON.md from the stored C2 artifacts.

Run after scripts.compare_losses. Every number is read from CSV/JSON artifacts;
interpretive sentences only restate quantities computed here.

    .venv\\Scripts\\python.exe -m scripts.write_loss_comparison_md
"""

from __future__ import annotations

import json

import numpy as np
import pandas as pd
import yaml

from src.utils.config import PROJECT_ROOT

E = PROJECT_ROOT / "results/classification/experiments"
ARMS = {"BCE": "c2a_bce", "WBCE": "c2b_sqrt_weighted_bce", "Focal": "c2c_focal_gamma2", "ASL": "c2d_asl"}
NAMES = {"BCE": "C2-A plain BCE", "WBCE": "C2-B √-weighted BCE", "Focal": "C2-C focal (γ=2)", "ASL": "C2-D ASL"}
RARE = ["Pleural Other", "Pneumonia", "Fracture", "Lung Lesion", "Enlarged Cardiomediastinum", "Consolidation"]
COMMON = ["Support Devices", "Lung Opacity", "Pleural Effusion", "Edema", "Atelectasis"]
f4 = lambda v: f"{v:.4f}"  # noqa: E731
sg = lambda v: f"{v:+.4f}"  # noqa: E731


def main() -> int:
    rd = lambda p: pd.read_csv(E / p, float_precision="round_trip")  # noqa: E731
    summ = rd("LOSS_COMPARISON.csv").set_index("arm")
    pc = rd("LOSS_COMPARISON_per_class.csv")
    boot = rd("LOSS_COMPARISON_bootstrap.csv")
    c1 = json.loads((E / "C1_REFERENCE.json").read_text(encoding="utf-8"))
    hist = {k: pd.read_csv(E / a / "training_history.csv") for k, a in ARMS.items()}
    cfg = {k: yaml.safe_load((E / a / "config.yaml").read_text(encoding="utf-8")) for k, a in ARMS.items()}
    ts = {k: json.loads((E / a / "training_summary.json").read_text(encoding="utf-8")) for k, a in ARMS.items()}
    meta = {k: json.loads((E / a / "checkpoints/best.meta.json").read_text(encoding="utf-8")) for k, a in ARMS.items()}
    w = rd("c2b_sqrt_weighted_bce/pos_weights_used.csv")
    S = {k: summ.loc[a] for k, a in ARMS.items()}
    top = max(S, key=lambda k: S[k]["macro_auprc"])
    b = lambda cmp, m: boot[(boot.comparison == cmp) & (boot.metric == m)].iloc[0]  # noqa: E731
    L = []
    A = L.append

    A("# C2 loss comparison: plain BCE vs √-weighted BCE vs focal vs ASL")
    A("")
    A("_Generated by `scripts/write_loss_comparison_md.py` from the stored artifacts. No locked-test data was used._")
    A("")
    A("**Question.** Can loss functions designed for class imbalance improve rare-finding discrimination in DenseNet121 on CheXpert without changing the data distribution?")
    A("")
    A("## 1. Design and control")
    A("")
    A("All four arms share one generated base config (`configs/classifier/c2/`). A test enforces that they differ **only** in `loss`, `experiment_name` and `output_dir`.")
    A("")
    A("Held fixed:")
    A("- DenseNet121 with ImageNet initialisation")
    A("- the Phase 1 patient-level train/validation split (133,644 / 28,671 frontal images)")
    A("- the 6 blank-image exclusions")
    A("- 224×224 aspect-preserving preprocessing")
    A("- the same augmentation")
    A("- the same label order")
    A("- uncertain → masked (zero loss and gradient), blank → 0")
    A("- AdamW (lr 1e-4, weight decay 1e-4), batch 32, AMP fp16 training")
    A("- ReduceLROnPlateau (factor 0.1, patience 1)")
    A("- 8 epochs maximum, early-stopping patience 3, seed 42")
    A("- TF32 off")
    A("- the same canonical `fp32_strict` evaluation")
    A("")
    A("Checkpoint selection, early stopping **and** the LR scheduler all monitor validation **macro AUPRC** in every arm.")
    A("")
    A("**Not a controlled comparison: C1.** C1 is shown only as an external historical reference. It was selected by macro AUROC and trained with TF32 on, so C1-vs-C2 differences are not a controlled loss comparison.")
    A("")
    A("**Reproducibility check.** C2-B is the same configuration as C1 apart from the selection metric. Its epochs 1–4 reproduce C1's training loss exactly to 4 decimals (0.5082, 0.4790, 0.4652, 0.4531). So training is deterministic across restarts and a reboot. C1's LR dropped after epoch 4; C2-B's dropped after epoch 6, which is why the later epochs diverge.")
    A("")
    A("## 2. Loss formulas and configurations (fixed before any C2 result)")
    A("")
    A("p = σ(z), z = logits. Every term is multiplied by the validity mask and divided by the number of valid entries.")
    A("")
    A("| Arm | Formula | Parameters |")
    A("|---|---|---|")
    A("| C2-A BCE | −[y log p + (1−y) log(1−p)] | none |")
    A("| C2-B √-weighted BCE | −[w_c·y log p + (1−y) log(1−p)], w_c = √(N_neg,c / N_pos,c) | counts from the TRAIN split only (valid entries; blank counted as negative, uncertain excluded) |")
    A("| C2-C focal | −(1−p_t)^γ log p_t | γ = 2.0, no α, no class weights |")
    A("| C2-D ASL (Ridnik et al. 2021 defaults) | y·[−(1−p)^γ⁺ log p] + (1−y)·[−p_m^γ⁻ log(1−p_m)], p_m = max(p − m, 0) | γ⁺ = 0, γ⁻ = 4, m (clip) = 0.05 |")
    A("")
    A("No ASL or focal parameter was tuned. The √ weighting for C2-B was chosen up front to match C1 and to avoid raw weights up to 74.8.")
    A("")
    A("**C2-B positive-class weights used** (`c2b_sqrt_weighted_bce/pos_weights_used.csv`):")
    A("")
    A("| Observation | N pos (train) | N neg (train) | raw N_neg/N_pos | **w = √raw (used)** |")
    A("|---|---:|---:|---:|---:|")
    for r in w.itertuples():
        A(f"| {r.observation} | {int(r.n_positive):,} | {int(r.n_negative):,} | {r.pos_weight_raw:.4f} | **{r.pos_weight_used:.4f}** |")
    A("")
    A("## 3. Overall results (canonical `fp32_strict` validation, 28,671 images)")
    A("")
    A("| Loss | Macro AUROC | Micro AUROC | **Macro AUPRC** | Micro AUPRC | Best epoch | Peak VRAM (GB) | Wall-clock (h)* |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|")
    for k in ARMS:
        s = S[k]
        A(f"| {NAMES[k]} | {f4(s.macro_auroc)} | {f4(s.micro_auroc)} | **{f4(s.macro_auprc)}** | {f4(s.micro_auprc)} | {int(s.best_epoch)} | {s.peak_vram_gb:.2f} | {s.training_hours:.2f} |")
    A(f"| _C1 external reference_ | {f4(c1['overall']['macro_auroc'])} | {f4(c1['overall']['micro_auroc'])} | {f4(c1['overall']['macro_auprc'])} | {f4(c1['overall']['micro_auprc'])} | 5 | 2.28 | 2.05 |")
    A("")
    A("\\* Wall-clock includes cold-disk first epochs and interruptions (see §7); it is **not** a loss-speed comparison.")
    A("")
    A("Machine-readable: `LOSS_COMPARISON.csv`. Checkpoint SHA-256 per arm is in that file and in each `checkpoint_sha256.json`.")
    A("")
    A("## 4. Complete per-class comparison (all 14 classes)")
    A("")
    A("### AUROC")
    A("")
    A("| Observation | Pos | Prevalence | BCE | √-WBCE | Focal | ASL | _C1 ref_ |")
    A("|---|---:|---:|---:|---:|---:|---:|---:|")
    for r in pc.itertuples():
        vals = [r.BCE_auroc, r.WBCE_auroc, r.Focal_auroc, r.ASL_auroc]
        cells = [f"**{f4(v)}**" if v == max(vals) else f4(v) for v in vals]
        A(f"| {r.observation} | {int(r.positive_support):,} | {r.prevalence:.4f} | {' | '.join(cells)} | {f4(r.C1ref_auroc)} |")
    A("")
    A("### AUPRC")
    A("")
    A("| Observation | Prevalence | BCE | √-WBCE | Focal | ASL | _C1 ref_ |")
    A("|---|---:|---:|---:|---:|---:|---:|")
    for r in pc.itertuples():
        vals = [r.BCE_auprc, r.WBCE_auprc, r.Focal_auprc, r.ASL_auprc]
        cells = [f"**{f4(v)}**" if v == max(vals) else f4(v) for v in vals]
        A(f"| {r.observation} | {r.prevalence:.4f} | {' | '.join(cells)} | {f4(r.C1ref_auprc)} |")
    A("")
    wins_ap = pc[["BCE_auprc", "WBCE_auprc", "Focal_auprc", "ASL_auprc"]].idxmax(axis=1).str.replace("_auprc", "").value_counts()
    wins_au = pc[["BCE_auroc", "WBCE_auroc", "Focal_auroc", "ASL_auroc"]].idxmax(axis=1).str.replace("_auroc", "").value_counts()
    A(f"Best loss per class (bold): AUPRC wins {wins_ap.to_dict()}; AUROC wins {wins_au.to_dict()}. Figures: `figures/per_class_auprc.png`, `figures/per_class_auroc.png`.")
    A("")
    A("## 5. Rare-class analysis")
    A("")
    A("Normalised lift = (AUPRC − prevalence) / (1 − prevalence): 0 is chance and 1 is perfect. AUPRC/prevalence overstates rare classes because its ceiling is 1/prevalence.")
    A("")
    A("| Observation | Prevalence | Loss | AUROC | AUPRC | AUPRC / prev. | Normalised lift | ΔAUPRC vs BCE |")
    A("|---|---:|---|---:|---:|---:|---:|---:|")
    pci = pc.set_index("observation")
    for lab in RARE:
        r = pci.loc[lab]
        for k in ARMS:
            ap, au = r[f"{k}_auprc"], r[f"{k}_auroc"]
            d = "n/a" if k == "BCE" else sg(ap - r["BCE_auprc"])
            A(f"| {lab} | {r.prevalence:.4f} | {k} | {f4(au)} | {f4(ap)} | {ap / r.prevalence:.2f} | {(ap - r.prevalence) / (1 - r.prevalence):.4f} | {d} |")
    A("")
    mean_rare = {k: pci.loc[RARE, f"{k}_auprc"].mean() for k in ARMS}
    A("Mean AUPRC over the six rare classes: " + ", ".join(f"{k} {f4(v)}" for k, v in mean_rare.items()) + ".")
    wb_gain = {lab: pci.loc[lab, "WBCE_auprc"] - pci.loc[lab, "BCE_auprc"] for lab in RARE}
    A("")
    A(f"- **√-WBCE** improves AUPRC over plain BCE in {sum(v > 0 for v in wb_gain.values())} of 6 rare classes, by {min(wb_gain.values()):+.4f} to {max(wb_gain.values()):+.4f}. The largest gain is {max(wb_gain, key=wb_gain.get)} ({max(wb_gain.values()):+.4f}). It is worse than BCE on AUROC for Pneumonia ({sg(pci.loc['Pneumonia', 'WBCE_auroc'] - pci.loc['Pneumonia', 'BCE_auroc'])}).")
    fo_gain = {lab: pci.loc[lab, "Focal_auprc"] - pci.loc[lab, "BCE_auprc"] for lab in RARE}
    A(f"- **Focal** is mixed: {sum(v > 0 for v in fo_gain.values())} of 6 up, {sum(v < 0 for v in fo_gain.values())} down (range {min(fo_gain.values()):+.4f} to {max(fo_gain.values()):+.4f}).")
    as_gain = {lab: pci.loc[lab, "ASL_auprc"] - pci.loc[lab, "BCE_auprc"] for lab in RARE}
    A(f"- **ASL** is up in {sum(v > 0 for v in as_gain.values())} of 6 and worst on Fracture ({sg(as_gain['Fracture'])}).")
    A("")
    A("**No rare class is \"solved\".** Every rare-class AUPRC stays below 0.21, with normalised lift at most 0.17, whichever loss is used. Per-class differences between losses were not tested for significance, so single-class gains are indicative only.")
    A("")
    A("## 6. Common-class regression check and statistical caution")
    A("")
    A("| Observation | Loss | ΔAUROC vs BCE | ΔAUPRC vs BCE |")
    A("|---|---|---:|---:|")
    for lab in COMMON:
        r = pci.loc[lab]
        for k in ("WBCE", "Focal", "ASL"):
            A(f"| {lab} | {k} | {sg(r[f'{k}_auroc'] - r['BCE_auroc'])} | {sg(r[f'{k}_auprc'] - r['BCE_auprc'])} |")
    A("")
    mean_common = {k: pci.loc[COMMON, f"{k}_auprc"].mean() for k in ARMS}
    A("Mean AUPRC over the five common classes: " + ", ".join(f"{k} {f4(v)}" for k, v in mean_common.items()) + ".")
    A("")
    A(f"- **√-WBCE** trades small losses on Support Devices ({sg(pci.loc['Support Devices','WBCE_auprc'] - pci.loc['Support Devices','BCE_auprc'])} AUPRC) and Pleural Effusion ({sg(pci.loc['Pleural Effusion','WBCE_auprc'] - pci.loc['Pleural Effusion','BCE_auprc'])}) for gains on Edema ({sg(pci.loc['Edema','WBCE_auprc'] - pci.loc['Edema','BCE_auprc'])}), Lung Opacity ({sg(pci.loc['Lung Opacity','WBCE_auprc'] - pci.loc['Lung Opacity','BCE_auprc'])}) and Atelectasis ({sg(pci.loc['Atelectasis','WBCE_auprc'] - pci.loc['Atelectasis','BCE_auprc'])}). There is no material common-class damage.")
    A(f"- **Micro metrics move the other way.** √-WBCE has the lowest micro AUROC ({f4(S['WBCE'].micro_auroc)} vs BCE {f4(S['BCE'].micro_auroc)}) and micro AUPRC ({f4(S['WBCE'].micro_auprc)} vs {f4(S['BCE'].micro_auprc)}). Micro metrics pool all (image, label) pairs, so they reward probabilities that are comparable **across** classes. Class weighting inflates rare-class probabilities relative to common ones, which hurts pooled ranking even though per-class discrimination improves.")
    A("- **Consequence for Phase 3:** per-class Youden thresholds are unaffected by this, but any use of raw probabilities across classes (for example ranking findings against each other) is.")
    A("")
    A("**Paired patient-level bootstrap** (1,000 resamples of the 9,530 validation patients, the same resample for every arm; difference of macro metrics, B − A):")
    A("")
    A("| Comparison | Metric | Δ | 95% CI | Share of resamples > 0 |")
    A("|---|---|---:|---|---:|")
    for r in boot.itertuples():
        A(f"| {r.comparison} | {r.metric.replace('macro_', 'macro ')} | {sg(r.point_estimate)} | [{sg(r.ci95_low)}, {sg(r.ci95_high)}] | {r.share_of_resamples_positive:.3f} |")
    A("")
    A("**What this does and doesn't show.**")
    A("- The intervals capture validation-sampling noise only.")
    A("- They do **not** capture training randomness. There is one seed per arm, so these are screening results, not proof of superiority.")
    A("- All macro-AUPRC differences between arms are at most 0.0085 (about 2% relative).")
    A("")
    A("## 7. Training behaviour")
    A("")
    A("| Loss | Best epoch | Epochs run | Final train loss | Val-loss min epoch | LR drops (epoch after which) | Max grad-norm | AMP-skipped steps | NaN/Inf | OOM |")
    A("|---|---:|---:|---:|---:|---|---:|---:|---|---|")
    for k in ARMS:
        h = hist[k]
        drops = [int(h.epoch[i]) for i in range(len(h) - 1) if h.lr[i + 1] < h.lr[i] * 0.5]
        A(f"| {k} | {ts[k]['best_epoch']} | {ts[k]['epochs_run']} | {h.train_loss.iloc[-1]:.4f} | {int(h.loc[h.val_loss.idxmin(), 'epoch'])} | {drops or 'none'} | {h.grad_norm_max.max():.2f} | {int(h.amp_skipped_or_nonfinite_steps.sum())} | none | none |")
    A("")
    A("Per-epoch tables are in each arm's `ANALYSIS.md` and `training_history.csv`. Curves: `figures/learning_curves_metrics.png`, `figures/learning_curves_loss.png`. Loss values are not comparable between loss functions, only the curve shapes are.")
    A("")
    A("**Stability.** No arm showed NaN/Inf, gradient explosion or OOM. " + "Maximum gradient norm per arm (always epoch 1): " + ", ".join(f"{k} {hist[k].grad_norm_max.max():.2f}" for k in ARMS) + "; after epoch 1 every arm stays below " + f"{max(hist[k].grad_norm_max.iloc[1:].max() for k in ARMS):.1f}" + ". Gradient scales differ between losses because the loss scales differ. A few AMP loss-scale skips (at most 3 per epoch) are normal fp16 calibration. All arms ran the full 8 epochs, so none stopped early.")
    A("")
    A("**Overfitting.** Mild in every arm: training loss falls monotonically, while validation loss reaches its minimum early (epoch 2–5) and then drifts up. Validation macro AUPRC plateaus at about 0.41–0.42 from epoch 5.")
    A("")
    A("**Underfitting.** None evident. But ASL's best epoch is the last (8), so it may still have been improving at the 8-epoch cap.")
    A("")
    A("**Scheduler confound.** The scheduler follows each arm's own validation metric, so the arms did not receive the same LR schedule. √-WBCE's LR dropped after epoch 6 and ASL's after epoch 7; BCE's and focal's never dropped. √-WBCE's best epoch (7) and ASL's best epoch (8) come right after those drops. Part of √-WBCE's lead over BCE may therefore reflect the LR decay rather than the loss. A confirmation run should fix the LR schedule to remove this.")
    A("")
    A("**Timing.** Peak VRAM is 2.28 GB for every arm. Steady-state epochs (2–8) averaged: " + ", ".join(f"{k} {hist[k][hist[k].epoch >= 2].train_seconds.mean() / 60:.1f} min" for k in ARMS) + " training plus about 1.7–2 min validation. Total wall-clock (§3) is inflated for BCE and √-WBCE by 55–65 min cold-disk first epochs, and the machine was interrupted during the study, so timing differences between arms are not attributable to the loss function and were not tested.")
    A("")
    A("**Run integrity.** Three runs were interrupted and restarted from scratch with identical configs: C2-A (stopped at the user's request), C2-B (the process died silently in epoch 7) and C2-C (killed by a laptop hard reset at 20:03). The partial outputs are kept under `_interrupted_*` and never used. Training is deterministic, so the completed runs match what an uninterrupted run would give (verified on C2-B vs C1, §1).")
    A("")
    A("## 8. Decision")
    A("")
    A("Rule applied (from the task): rank on (1) macro AUPRC, (2) per-class AUPRC, (3) rare-class improvement, (4) common-class regression, (5) macro AUROC, (6) stability, (7) magnitude of improvement over baseline.")
    A("")
    A("| Loss | Macro AUPRC | Δ vs BCE [95% CI] | Rare-6 mean AUPRC | Common-5 mean AUPRC | Macro AUROC | Verdict |")
    A("|---|---:|---|---:|---:|---:|---|")
    ci = lambda k, m: b(f"{k} - BCE", m)  # noqa: E731
    verdict = {"BCE": "control", "WBCE": "**lead candidate**", "Focal": "**second candidate**",
               "ASL": "**not promoted** (as configured)"}
    for k in ARMS:
        if k == "BCE":
            A(f"| BCE | {f4(S[k].macro_auprc)} | n/a | {f4(mean_rare[k])} | {f4(mean_common[k])} | {f4(S[k].macro_auroc)} | {verdict[k]} |")
        else:
            r = ci(k, "macro_auprc")
            A(f"| {k} | {f4(S[k].macro_auprc)} | {sg(r.point_estimate)} [{sg(r.ci95_low)}, {sg(r.ci95_high)}] | {f4(mean_rare[k])} | {f4(mean_common[k])} | {f4(S[k].macro_auroc)} | {verdict[k]} |")
    A("")
    wbce_au = b("WBCE - BCE", "macro_auroc")
    fo_au = b("Focal - BCE", "macro_auroc")
    A("**Recommendation: carry two losses forward, √-weighted BCE and focal (γ = 2), to multi-seed confirmation, with plain BCE as the control.**")
    A("")
    A(f"- **√-weighted BCE (lead).**")
    A(f"  - It has the highest macro AUPRC ({f4(S['WBCE'].macro_auprc)}; {sg(ci('WBCE', 'macro_auprc').point_estimate)} over BCE, CI excludes 0).")
    A(f"  - It improves AUPRC in all six rare classes, with the best result on 8 of 14 classes by AUPRC and AUROC.")
    A(f"  - Macro AUROC is up only {sg(wbce_au.point_estimate)} (CI [{sg(wbce_au.ci95_low)}, {sg(wbce_au.ci95_high)}]), so the gain is modest and the AUROC part is not established.")
    A(f"  - Its costs are the lowest micro metrics (cross-class probabilities are less comparable) and the scheduler confound in §7.")
    A(f"- **Focal.**")
    A(f"  - It is a close second on macro AUPRC ({f4(S['Focal'].macro_auprc)}). Against BCE the difference is {sg(ci('Focal', 'macro_auprc').point_estimate)}, CI [{sg(ci('Focal', 'macro_auprc').ci95_low)}, {sg(ci('Focal', 'macro_auprc').ci95_high)}], so it is not distinguishable from BCE here.")
    A(f"  - It is stable (no instability in training) and it preserves cross-class probabilities (its micro metrics match BCE).")
    A(f"  - It deserves a second look because the √-WBCE result may be partly scheduler-driven. A multi-seed run decides whether focal's small edge is real.")
    A(f"- **ASL, as configured (γ⁺ 0, γ⁻ 4, clip 0.05).** It is lowest on macro AUROC and macro AUPRC ({f4(S['ASL'].macro_auprc)}); its AUROC deficit against BCE is {sg(b('ASL - BCE', 'macro_auroc').point_estimate)} (CI excludes 0). It is worst on Fracture and Cardiomegaly. This is a statement about one fixed configuration within an 8-epoch budget, not about ASL in general: its best epoch was the last one.")
    A(f"- **Plain BCE** is competitive: within 0.006 macro AUPRC of the best arm, and best on micro AUROC and Support Devices. The gains from the imbalance losses are small.")
    A("")
    A("**Next experiment (needs your approval, not started).**")
    A("- Multi-seed (for example 3 seeds) of √-WBCE, focal and the BCE control.")
    A("- Fix the LR schedule identically across arms, to remove the scheduler confound.")
    A("- Report patient-bootstrap CIs plus across-seed variation.")
    A("- Threshold optimisation stays separate and comes after the loss choice.")
    A("")
    A("## 9. Limitations")
    A("")
    A("- One seed per arm, so there is no training-variance estimate.")
    swing = {k: float(hist[k].val_macro_auprc.diff().abs().iloc[1:].median()) for k in ARMS}
    A("- **Epoch-to-epoch noise is comparable to the gaps between arms.** The median absolute epoch-to-epoch change in validation macro AUPRC (epochs 2–8) is " + ", ".join(f"{k} {v:.4f}" for k, v in swing.items()) + ", against between-arm gaps of 0.002–0.008. Taking the best of 8 epochs also gives each arm a selection-optimistic number (best epoch vs the following epoch: " + ", ".join((f"{k} {hist[k].val_macro_auprc.max():.4f} vs {hist[k].val_macro_auprc.iloc[int(ts[k]['best_epoch'])]:.4f}" if int(ts[k]['best_epoch']) < 8 else f"{k} {hist[k].val_macro_auprc.max():.4f} vs n/a (best was the last epoch)") for k in ARMS) + "). The ranking is therefore a screening signal, not a verdict.")
    A("- The scheduler confound described in §7.")
    A("- Labels come from an automatic report labeler with blank scored as negative, so false-negative noise affects every class.")
    A("- Validation-set metrics only. The locked test split was never opened.")
    A("- ASL was evaluated at one standard configuration only, with no tuning by design.")
    A("")
    A("## 10. Provenance")
    A("")
    A("| Arm | Checkpoint SHA-256 | Code commit in checkpoint |")
    A("|---|---|---|")
    for k, a in ARMS.items():
        sha = json.loads((E / a / "checkpoint_sha256.json").read_text(encoding="utf-8"))["best.pt"]["sha256"]
        A(f"| {NAMES[k]} | `{sha}` | `{meta[k]['git_commit'][:12]}` |")
    A("")
    A("Evaluation policy: `fp32_strict` (fp32, no autocast, TF32 off, deterministic cuDNN). Predictions stored losslessly (`evaluation/fp32_strict/validation_predictions.npz`).")
    A("")
    (E / "LOSS_COMPARISON.md").write_text("\n".join(L), encoding="utf-8")
    print("wrote", E / "LOSS_COMPARISON.md", "|", len(L), "lines | top macro AUPRC:", top)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
